### ISSUE TITLE
How to use glob pattern without archiving all files into a single artifact?

### ISSUE THREAD

**Issue by dotansimha** [actions/upload-artifact#101]
**Describe the bug**

Related: https://github.com/actions/upload-artifact/issues/3

Is is possible to disable the archiving step with v2? 
I have multiple `.tgz` files in my repo, and I would like to upload it as-is, as multiple artifacts, and not as a single one. 
I'm using a glob pattern: `*.tgz` for that, but the result is a single artifact, called `artifact`, with all files inside, instead of having multiple artifacts. 
The goal is to have access to those files directly.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
https://github.com/dotansimha/graphql-code-generator/pull/4435/checks?check_run_id=913862232

**How to reproduce**

Multiple files matches the glob pattern, with this config:

```
      - uses: actions/upload-artifact@v2
        with:
          path: '*.tgz'
```

**Additional context**

**Comment by konradpabjan** [comment]
Closing this as a dup of https://github.com/actions/upload-artifact/issues/109 and https://github.com/actions/upload-artifact/issues/39

It is not possible to currently download something other than a zip. Some more information here and in the linked issues: https://github.com/actions/upload-artifact#zipped-artifact-downloads

During upload, there is no zip created and all files are uploaded individually. The zip you get is a current limitation of our UI
