### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by roedoejet** [actions/upload-artifact#110]
**Describe the bug**
I am getting a warning with the following:

`##[warning]No files were found with the provided path: $GITHUB_WORKSPACE/artifacts/Convertextract-macOS.zip. No artifacts will be uploaded.`

But, as you can see in the screenshot below - there is definitely a file there. I have tried uploading the artifact as a directory, (ie changing the path to `$GITHUB_WORKSPACE/artifacts/`) but the problem still occurs. I've also tried zipping it as with this [most recent workflow run](https://github.com/roedoejet/convertextract/runs/955412706?check_suite_focus=true), and leaving it un-zipped as in [this workflow run](https://github.com/roedoejet/convertextract/runs/955250462?check_suite_focus=true).

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

**Screenshots**
Below is a screenshot showing that the file *is* there, but the artifacts action does not find it.

![image](https://user-images.githubusercontent.com/14815080/89576249-e3f12080-d7e3-11ea-8af9-4638bd15b1a3.png)

**Run/Repo Url**
https://github.com/roedoejet/convertextract/runs/955412706?check_suite_focus=true

**How to reproduce**
The GitHub action is public, as is the repo.

**Additional context**
None. Thanks for such a great tool!

**Comment by roedoejet** [comment]
Thanks to @eddieantonio, I found the relevant documentation: https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion !

**Comment by lipalath-ms** [comment]
I'm having a similar issue. Here is my yaml code:

```
name: CI

on:
  push:
    branches:
    - master

jobs:
  GMMBuildAndRelease:
    strategy:
      matrix:
        BuildConfiguration:
        - debug
        - release
      max-parallel: 2

    runs-on: windows-2019

    steps:
    
    - name: Checkout Action
      uses: actions/checkout@v1
    
    - name: List contents of a folder
      run: dir

    - name: copy arm templates
      run: Copy 'Infrastructure/' '${GITHUB_WORKSPACE}/Infrastructure'
      shell: powershell

    - name: copy release management scripts
      run: Copy 'Scripts/' '${GITHUB_WORKSPACE}/Scripts'
      shell: powershell

    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${GITHUB_WORKSPACE}
        name: ${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}
```

On running this, I see the error: No files were found with the provided path: ${GITHUB_WORKSPACE}. No artifacts will be uploaded.

On checking the contents in this folder, I see Infrastructure and Scripts folders exist:

![image](https://user-images.githubusercontent.com/6519992/93949350-6763c400-fcf5-11ea-8145-0bb67a40352c.png)

What am I missing? Please help.

**Comment by IgorGanapolsky** [comment]
I am having the same problem for `mapping.txt` file in Android release bundle.  It gives the same error.

**Comment by Crishpy-Coffe** [comment]
galtiya sbki niklli hai , koi answer bhi likh doo km se km

**Comment by yuriysurzhikov** [comment]
Still have the same issue when trying to archive apk file after build
![image](https://user-images.githubusercontent.com/44873047/187893867-ad063dba-6dc9-49bb-ade6-40e3b3b09b4c.png)
And here is my step code:
![image](https://user-images.githubusercontent.com/44873047/187893979-8af8ab2a-f949-4036-915e-7823159dba8f.png)
