### ISSUE TITLE
Recurring ETIMEDOUT errors even with 20kb archives, not retry

### ISSUE THREAD

**Issue by ssbarnea** [actions/upload-artifact#123]
**Describe the bug**
I see quite often failures to upload log which look like:

```
Run actions/upload-artifact@v2
  with:
    name: logs.zip
    path: .tox/**/log/
    if-no-files-found: warn
  env:
    TOX_PARALLEL_NO_SPINNER: 1
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.6.12/x64
With the provided path, there will be 27 file(s) uploaded
Total size of all the files uploaded is 24487 bytes
##[error]connect ETIMEDOUT 13.107.42.16:443
```

**Version**
- [x] V2

**Environment**
- [x] Mac

**Additional context**
I am not sure if that happens only on macos hosts but it would not be a surprise as I seen other reliability issues particular to macos workers.

Still, the main issue here is that the tool does not support any retry mechanism. As any networking operation can be subject to temporary glitches the upload must be able to retry. Probably a 3 retries with a 10s back-off would be fine, even if hardcoded.

**Comment by fornwall** [comment]
I'm observing the same sporadic issue on macOS runners.

**Comment by tjanez** [comment]
I've observed the same thing with macOS runners.

Currently, I only have a private workflow, so can't link to the failed job(s) at the moment.

**Comment by wjakob** [comment]
(Also running into this.)

**Comment by konradpabjan** [comment]
This should now be fixed, see: https://github.com/actions/upload-artifact/issues/116#issuecomment-754141048

Please open a new issue if `ETIMEDOUT` comes up again
