### ISSUE TITLE
I am having this issue with my project with github actions

### ISSUE THREAD

**Issue by yunior123** [actions/upload-artifact#124]
This is the error, the path does not exist
##[error]Path does not exist /home/runner/work/t-rr/build/app/outputs/flutter-apk/app-release.apk
##[error]Exit code 1 returned from process: file name '/home/runner/runners/21/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

**Version**
- [ ]I am using flutter version 1.20.3

**Environment**
 -[ ] Linux
- [ ] Windows

**Screenshots**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**

**Comment by konradpabjan** [comment]
That error can happen if you use the `v1` version of `upload-artifact`. I would suggest switching over to the `v2` version (`@actions/upload-artifact@v2`).

My suspicion is that you provided a path that was empty/invalid. If you use the `v2` version and you provide an invalid path, the error message is clearer
