### ISSUE TITLE
Artifact upload occasionally fails

### ISSUE THREAD

**Issue by chingc** [actions/upload-artifact#135]
**Describe the bug**
Artifact upload occasionally fails.  It doesn't happen often but it's annoying when it does.
Re-running the build fixes the issue everytime.

I think it would be nice to see an automatic retry feature enabled by default so that an entire build doesn't fail.

Here's the error I got:
```
Error: Unable to create a container for the artifact artifact at https://pipelines.actions.githubusercontent.com/j744JdjP7hmWpDAk1yany53cI07tMYFojlKbSemW7bhUQQz7hi/_apis/pipelines/workflows/304930541/artifacts?api-version=6.0-preview
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Comment by tobstarr** [comment]
I keep on constantly running into this one as well and I already tried to re-run the test a couple of times without any success.

**Comment by tobstarr** [comment]
What did help is actually (force) pushing some change into the branch and after that the tests step passed again.

**Comment by konradpabjan** [comment]
Fixed! See: https://github.com/actions/upload-artifact/issues/116#issuecomment-754141048
