### ISSUE TITLE
v2 failing uploads right now: 503 Service Unavailable

### ISSUE THREAD

**Issue by altendky** [actions/upload-artifact#136]
**Describe the bug**
There seems to be a problem with v2 uploads right now.  v1 seems ok.  A couple work each run but most fail.

Ok with v1: https://github.com/altendky/pyqt5-tools/runs/1250093808
Bad with v2: https://github.com/altendky/pyqt5-tools/actions/runs/303395415

```
Run actions/upload-artifact@v2
  with:
    name: pyqt5_tools-all_wheels
    path: dist
    if-no-files-found: warn
  env:
    PIP_NO_PYTHON_VERSION_WARNING: 1
    QT_VERSION: 5.14.0
    BUILD_PATH: /tmp/pip-req-build-erpql1xn
/usr/bin/docker exec  ece1741956b10ba4ef7924e97e98b7e8e2118d00ef0a9c232defe0c99a1471ab sh -c "cat /etc/*release | grep ^ID"
With the provided path, there will be 1 file(s) uploaded
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 5256.271835568903 milliseconds before continuing the upload at offset 92274688
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #1, continuing with upload
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #2. Waiting for 11817.944357135919 milliseconds before continuing the upload at offset 92274688
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #2, continuing with upload
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #3. Waiting for 15452.962036789748 milliseconds before continuing the upload at offset 92274688
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #3, continuing with upload
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #4. Waiting for 19383.296514502406 milliseconds before continuing the upload at offset 92274688
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #4, continuing with upload
A 503 status code has been received, will attempt to retry the upload
Exponential backoff for retry #5. Waiting for 23231.805179610954 milliseconds before continuing the upload at offset 92274688
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Finished backoff for retry #5, continuing with upload
A 503 status code has been received, will attempt to retry the upload
##### Begin Diagnostic HTTP information #####
Status Code: 503
Status Message: Service Unavailable
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "357",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "e63482a6-a6f9-4eb0-a933-79e06977479e",
  "activityid": "3fe86909-5ff0-4829-abf7-dde179f6a150",
  "x-tfs-session": "3fe86909-5ff0-4829-abf7-dde179f6a150",
  "x-vss-e2eid": "3fe86909-5ff0-4829-abf7-dde179f6a150",
  "x-vss-senderdeploymentid": "02120909-3c00-63c2-b451-f147b8aff5a4",
  "x-frame-options": "SAMEORIGIN",
  "x-msedge-ref": "Ref A: E32C67E330A047B7919B29C37B8FE46B Ref B: BN3EDGE0216 Ref C: 2020-10-13T21:32:10Z",
  "date": "Tue, 13 Oct 2020 21:32:10 GMT"
}
###### End Diagnostic HTTP information ######
Retry limit has been reached for chunk at offset 92274688 to https://pipelines.actions.githubusercontent.com/pPte4Jtcr9As0jTpY5kCoNKyfpGTePSKeuSWwwpdithKTMCHNa/_apis/resources/Containers/7845729?itemPath=pyqt5_tools-all_wheels%2Fpyqt5_tools-5.14.1.1.7.5.post21-py3-none-manylinux2014_x86_64.whl
Warning: Aborting upload for /__w/pyqt5-tools/pyqt5-tools/dist/pyqt5_tools-5.14.1.1.7.5.post21-py3-none-manylinux2014_x86_64.whl due to failure
Error: aborting artifact upload
Total size of all the files uploaded is 92274688 bytes
Finished uploading artifact pyqt5_tools-all_wheels. Reported size is 92274688 bytes. There were 1 items that failed to upload
Error: An error was encountered when uploading pyqt5_tools-all_wheels. There were 1 items that failed to upload.
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [x] Windows
- [ ] Mac

**Comment by altendky** [comment]
Nevermind, neither is working.  v1 doesn't fail out the build, but the artifact is reported too small in the web ui and fails to be opened when I download it.

**Comment by Tarsmash** [comment]
> **Describe the bug**
> There seems to be a problem with v2 uploads right now. v1 seems ok. A couple work each run but most fail.
> 
> Ok with v1: https://github.com/altendky/pyqt5-tools/runs/1250093808
> Bad with v2: https://github.com/altendky/pyqt5-tools/actions/runs/303395415
> 
> ```
> Run actions/upload-artifact@v2
>   with:
>     name: pyqt5_tools-all_wheels
>     path: dist
>     if-no-files-found: warn
>   env:
>     PIP_NO_PYTHON_VERSION_WARNING: 1
>     QT_VERSION: 5.14.0
>     BUILD_PATH: /tmp/pip-req-build-erpql1xn
> /usr/bin/docker exec  ece1741956b10ba4ef7924e97e98b7e8e2118d00ef0a9c232defe0c99a1471ab sh -c "cat /etc/*release | grep ^ID"
> With the provided path, there will be 1 file(s) uploaded
> Total file count: 1 ---- Processed file #0 (0.0%)
> Total file count: 1 ---- Processed file #0 (0.0%)
> A 503 status code has been received, will attempt to retry the upload
> Exponential backoff for retry #1. Waiting for 5256.271835568903 milliseconds before continuing the upload at offset 92274688
> Total file count: 1 ---- Processed file #0 (0.0%)
> Finished backoff for retry #1, continuing with upload
> A 503 status code has been received, will attempt to retry the upload
> Exponential backoff for retry #2. Waiting for 11817.944357135919 milliseconds before continuing the upload at offset 92274688
> Total file count: 1 ---- Processed file #0 (0.0%)
> Finished backoff for retry #2, continuing with upload
> A 503 status code has been received, will attempt to retry the upload
> Exponential backoff for retry #3. Waiting for 15452.962036789748 milliseconds before continuing the upload at offset 92274688
> Total file count: 1 ---- Processed file #0 (0.0%)
> Finished backoff for retry #3, continuing with upload
> A 503 status code has been received, will attempt to retry the upload
> Exponential backoff for retry #4. Waiting for 19383.296514502406 milliseconds before continuing the upload at offset 92274688
> Total file count: 1 ---- Processed file #0 (0.0%)
> Total file count: 1 ---- Processed file #0 (0.0%)
> Finished backoff for retry #4, continuing with upload
> A 503 status code has been received, will attempt to retry the upload
> Exponential backoff for retry #5. Waiting for 23231.805179610954 milliseconds before continuing the upload at offset 92274688
> Total file count: 1 ---- Processed file #0 (0.0%)
> Total file count: 1 ---- Processed file #0 (0.0%)
> Total file count: 1 ---- Processed file #0 (0.0%)
> Finished backoff for retry #5, continuing with upload
> A 503 status code has been received, will attempt to retry the upload
> ##### Begin Diagnostic HTTP information #####
> Status Code: 503
> Status Message: Service Unavailable
> Header Information: {
>   "cache-control": "no-store,no-cache",
>   "pragma": "no-cache",
>   "content-length": "357",
>   "content-type": "application/json; charset=utf-8",
>   "strict-transport-security": "max-age=2592000",
>   "x-tfs-processid": "e63482a6-a6f9-4eb0-a933-79e06977479e",
>   "activityid": "3fe86909-5ff0-4829-abf7-dde179f6a150",
>   "x-tfs-session": "3fe86909-5ff0-4829-abf7-dde179f6a150",
>   "x-vss-e2eid": "3fe86909-5ff0-4829-abf7-dde179f6a150",
>   "x-vss-senderdeploymentid": "02120909-3c00-63c2-b451-f147b8aff5a4",
>   "x-frame-options": "SAMEORIGIN",
>   "x-msedge-ref": "Ref A: E32C67E330A047B7919B29C37B8FE46B Ref B: BN3EDGE0216 Ref C: 2020-10-13T21:32:10Z",
>   "date": "Tue, 13 Oct 2020 21:32:10 GMT"
> }
> ###### End Diagnostic HTTP information ######
> Retry limit has been reached for chunk at offset 92274688 to https://pipelines.actions.githubusercontent.com/pPte4Jtcr9As0jTpY5kCoNKyfpGTePSKeuSWwwpdithKTMCHNa/_apis/resources/Containers/7845729?itemPath=pyqt5_tools-all_wheels%2Fpyqt5_tools-5.14.1.1.7.5.post21-py3-none-manylinux2014_x86_64.whl
> Warning: Aborting upload for /__w/pyqt5-tools/pyqt5-tools/dist/pyqt5_tools-5.14.1.1.7.5.post21-py3-none-manylinux2014_x86_64.whl due to failure
> Error: aborting artifact upload
> Total size of all the files uploaded is 92274688 bytes
> Finished uploading artifact pyqt5_tools-all_wheels. Reported size is 92274688 bytes. There were 1 items that failed to upload
> Error: An error was encountered when uploading pyqt5_tools-all_wheels. There were 1 items that failed to upload.
> ```
> 
> **Version**
> 
> * [ ]  V1
> * [x]  V2
> 
> **Environment**
> 
> * [ ]  self-hosted
> * [x]  Linux
> * [x]  Windows
> * [ ]  Mac

okay let try another one

**Comment by boardfish** [comment]
```
Run actions/upload-artifact@v2
  with:
    name: coverage-report
    path: coverage/index.html
    if-no-files-found: warn
With the provided path, there will be 1 file(s) uploaded
##### Begin Diagnostic HTTP information #####
Status Code: 503
Status Message: Service Unavailable
Header Information: {
  "content-length": "303",
  "content-type": "application/json",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "4642aaa7-c4b0-44f7-8648-9fea017d5a1e",
  "x-tfs-serviceerror": "An+Internal+Error+Occurred.",
  "x-msedge-ref": "Ref A: 3FC9A6894C0D4F39AA2331F16D18E19C Ref B: BN3EDGE0906 Ref C: 2020-11-16T18:45:43Z",
  "date": "Mon, 16 Nov 2020 18:45:42 GMT",
  "connection": "close"
}
###### End Diagnostic HTTP information ######
Error: Unable to create a container for the artifact coverage-report at https://pipelines.actions.githubusercontent.com/...
```

This seems to have made a resurgence. Nothing's reported on status.github.com in the way of outages.

**Comment by kyranjamie** [comment]
Experiencing this on some MacOS builds as well, see example build here https://github.com/blockstack/stacks-wallet/runs/1584612987

**Comment by konradpabjan** [comment]
Some recent work was done to improve retryability and error handling if a 503 is encountered (see the [v2.2.2](https://github.com/actions/upload-artifact/releases/tag/v2.2.2) release). Closing out for now, please open a new issue if this comes up.
