### ISSUE TITLE
getting link to uploaded doc

### ISSUE THREAD

**Issue by mimoo** [actions/upload-artifact#141]
Hello,

I wanted to know if it was possible to output the link to the uploaded document

Thanks!

**Comment by mimoo** [comment]
(I can get the run id via GITHUB_RUN_ID, but not the artifact id)

**Comment by konradpabjan** [comment]
There is no easy way to currently get the link after you upload an artifact other than through the UI

You can use our APIs though to download the artifact: https://developer.github.com/v3/actions/artifacts/#artifacts

If you need an exact URL, you might be able to create it yourself using this: https://github.com/actions/upload-artifact/issues/89#issuecomment-654357678
