### ISSUE TITLE
Status Code: 400 Status Message: Bad Request

### ISSUE THREAD

**Issue by abhikanojia** [actions/upload-artifact#143]
**Describe the bug**
With the provided path, there will be 1 file(s) uploaded
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Error: Unable to create a container for the artifact

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**

**Comment by konradpabjan** [comment]
Need more information (the run URL, a screenshot or something?) Without that we are an unable to investigate further. Please re-open if this continues to be an error
