### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by newhoggy** [actions/upload-artifact#146]
Use of `upload-artifact` can fail with ECONNRESET.

![image](https://user-images.githubusercontent.com/63014/99015522-50c94300-25a9-11eb-9c0a-e3afce55372f.png)

The expectation is that this action should never fail when used correctly.

The failure can be see here:  https://github.com/input-output-hk/cardano-node/pull/2083/checks?check_run_id=1393451383

**Comment by konradpabjan** [comment]
Duplicate: https://github.com/actions/upload-artifact/issues/116
