### ISSUE TITLE
Problems with file name

### ISSUE THREAD

**Issue by Neskelogth** [actions/upload-artifact#155]
I have a repo that needs to upload an artifact with the name depending on the last pushed file. Is it possible to do that and rename the output like this? For example if the last pushed file is called "File.tex" I would like to call the output "File.pdf". Can I do this?

**Comment by konradpabjan** [comment]
Not possible to do that and I can't think of any tricks that you could use to achieve the desired outcome.

We also don't have any API to rename an artifact after it has been uploaded
