### ISSUE TITLE
Discrepancy between reported size by commandline output and actual artifact size

### ISSUE THREAD

**Issue by asdfCYBER** [actions/upload-artifact#158]
**Describe the bug**
The reported size as shown in the step-output is different from the size of the artifact available to download. For instance, when the reported size is "1926874 bytes", the size of the downloadable artifact is reported as 17.1 MB, which is roughly 9 times larger than expected. When downloading, the .zip is reported as 1893 kB by Windows. The unzipped files are about 17.6 MB according to Windows. I'm not sure if this is a bug in this action or in GitHub Actions in general (or perhaps even both), but I think it should be addressed.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Run/Repo Url**
Action output: https://github.com/asdfCYBER/NetFramework-GithubActions/runs/1582352208?check_suite_focus=true#step:7:9
Artifact size: https://github.com/asdfCYBER/NetFramework-GithubActions/actions/runs/432804099

**How to reproduce**
Use this action to upload an artifact

**Comment by konradpabjan** [comment]
The reported size is correct.

I've added some more documentation to the `README`: https://github.com/actions/upload-artifact#where-does-the-upload-go

> The size of the artifact is denoted in bytes. The displayed artifact size denotes the raw uploaded artifact size (the sum of all the individual files uploaded during the workflow run for the artifact), not the compressed size. When you click to download an artifact from the summary page, a compressed zip is created with all the contents of the artifact and the size of the zip that you download may differ significantly from the displayed size. Billing is based on the raw uploaded size and not the size of the zip.

This has previously come up as well, see: https://github.com/actions/upload-artifact/issues/26
