### ISSUE TITLE
Allow ommitting the path

### ISSUE THREAD

**Issue by leonardder** [actions/upload-artifact#16]
It is now required to provide a path for every artifact you upload. I have a repository where the artifacts are ending up in the root of the git repository (it is a fairly small project). I would expect the default path to be the git repository and a possible override of the path being relative to it, but this might not be true, it is not documented that clearly. Anyway, if the artifacts to upload are in a default path, specifying the path is redundant.

**Comment by konradpabjan** [comment]
Path omission is something we are not going to add.

When you use `actions/checkout` to checkout your git repository, everything gets put into `$GITHUB_WORKSPACE`. If the default upload path was set to the same thing, users would be uploading effectively what they just checked out and we don't want to encourage the practice (most likely with some new files etc., but the majority of what they upload would be equal to what they checked out). Most repositories are small, but this behavior could be very problematic for users who are checking out big repositories and hit quotas with the artifacts they produce.

Artifacts are meant to be things other than source code such as test output or build output. When you run tests or a build, you can (most of the time) specify where you want that output to go and later use that as the PATH input when uploading an artifact. Before upload, you can also separately move the files that end up in the root git directory to some other directory. 

Overall, we want users to be explicit with what they upload and having the default path set to the git repository could cause of a lot of users to upload source code that they just checked out.
