### ISSUE TITLE
503s on Large Uploads

### ISSUE THREAD

**Issue by ivan-c** [actions/upload-artifact#168]
**Describe the bug**
I'm unable to upload a system image file (~3GB) generated from qemu/packer.

Every GitHub Actions run I've tested has failed with `503 Service Unavailable` at ~99% upload completion.

I've read the documentation, but I haven't found any limitations around artifact filesize, so I'm assuming it's still possible to upload a build artifact as large as 5-10GB.
**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
[GitHub Action Run URL](https://github.com/ivan-c/raspi-packer-templates/runs/1759261350)

**Additional context**
The raw image I'm uploading is a sparse file, preallocated as 8GB but only ~3GB in actuality.

**Comment by konradpabjan** [comment]
We've made of a lot of changes recently that should reduce the number of 503s that are experienced and internal telemetry shows this is happening very very infrequently. If you hit this problem again please open a new issue 🙇‍♂️
