### ISSUE TITLE
Wildcard in artifact name

### ISSUE THREAD

**Issue by Xottab-DUTY** [actions/upload-artifact#169]
Currently, it is possible to use wildcards in the path, but it also will be nice to have wildcard support in the artefact name! (at least `*`)

**Comment by konradpabjan** [comment]
We won't be supporting this. Certain characters do not play well with different file systems which is why the restriction is in place.

https://github.com/actions/upload-artifact/blob/ea3d524381d563437a7d64af63f3d75ca55521c4/dist/index.js#L8328-L8341
