### ISSUE TITLE
Consistently failing uploads on matrix workflow

### ISSUE THREAD

**Issue by jasonkuhrt** [actions/upload-artifact#175]
**Describe the bug**

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/284476/107457426-0ad83880-6b20-11eb-9819-7d67650276e9.png">

**Additional context**

We are running a matrix of 36 jobs and basically are blocked right now as GitHub is repeatedly failing to get through the matrix without 1-3 failures.

**Comment by Serhii-Sokolov-McK** [comment]
We have the same issue. It seems that if new file was uploaded to workspace and 1-2 seconds later another job tries to download this file action fails.

**Comment by konradpabjan** [comment]
v4 has shipped today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over as these classes of issues should no longer happen with the release. v4 is orders of magnitude faster and more reliable
