### ISSUE TITLE
Allow disabling the archiving stage.

### ISSUE THREAD

**Issue by NikitkoCent** [actions/upload-artifact#19]
Sometimes it would be useful to publish artifact without archiving it, e.g. when artifact is a single file, or I created the archive by myself (for example, I want to archive to `.tar.gz` on Ubuntu/macOS jobs and to `.zip` on Windows).

**Comment by 0xd4d** [comment]
Duplicate of https://github.com/actions/upload-artifact/issues/3

**Comment by NikitkoCent** [comment]
Ok, I got it.
I close the issue.
