### ISSUE TITLE
Glob Pattern Severely Broken in V1 on Windows

### ISSUE THREAD

**Issue by sr229** [actions/upload-artifact#193]
**Describe the bug**
Trying to match glob patterns in Windows even if it's a valid directory results in the script thinking it's not a valid file directory.

**Version**
- [x] V1
- [ ] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Screenshots**
![image](https://user-images.githubusercontent.com/14976516/116257915-0c241380-a7a7-11eb-84ec-32fe5b2c346a.png)
![image](https://user-images.githubusercontent.com/14976516/116257998-1f36e380-a7a7-11eb-9b4e-444eaecd924b.png)

**Run/Repo Url**
https://github.com/vignette-project/osu-framework/runs/2447974801?check_suite_focus=true

**Comment by konradpabjan** [comment]
v1 does not support tags. It was only added as part of `v2`

https://github.com/actions/upload-artifact/tree/releases/v1

In the "what's new section" for the `REAMDE` you can see:

> Specify a wildcard pattern
