### ISSUE TITLE
zipped artifact file is not getting downloaded

### ISSUE THREAD

**Issue by immanishbainsla** [actions/upload-artifact#207]
**Describe the bug**
after test run it shows original artifact file size is 245MB but when i download it, it gets downloaded as only 22bits of size.
workflow run : https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/actions/runs/863711441
(also as I trying it for first time I am not sure) artifact file name is "zip" without any extension/file type. Is that normal or a bug?

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Comment by konradpabjan** [comment]
The is the current behavior. The `README` discusses both of these behaviors

Regarding the zip file that is created for download:
https://github.com/actions/upload-artifact#zipped-artifact-downloads

Regarding the artifact size that is reported:
https://github.com/actions/upload-artifact#where-does-the-upload-go

> The displayed artifact size denotes the raw uploaded artifact size (the sum of all the individual files uploaded during the workflow run for the artifact), not the compressed size. When you click to download an artifact from the summary page, a compressed zip is created with all the contents of the artifact and the size of the zip that you download may differ significantly from the displayed size. Billing is based on the raw uploaded size and not the size of the zip.
