### ISSUE TITLE
Remove this 'There were 0 items that failed to upload' message

### ISSUE THREAD

**Issue by simonmeggle** [actions/upload-artifact#208]
I don't know how others think about this minor request, but I think a successful artifact upload should not contain negative words. 
Depending on the line break a successful upload is shown as

```
Total size of all the files uploaded is 40292 bytes
Finished uploading artifact cmk1-9c32221.mkp. Reported size is 40292 bytes. There were 0 items that  # << line break!!
failed to upload          # << Hugh?! :-o
Artifact cmk1-9c32221.mkp has been successfully uploaded!
```

`failed to upload` is what catches the eye first and raises unnecessary attention if everything was OK. 
_If_ there are any errors, the message makes sense, of course.

**Comment by konradpabjan** [comment]
Done! Thanks for the suggestion. The output towards the end looks now something like this (has a lot more information and doesn't have the failed message if not applicable)

![image](https://user-images.githubusercontent.com/16109154/145150018-cec40f2f-935c-4311-bb01-abff6c4b5c28.png)
