### ISSUE TITLE
Temporary files are not removed when run is cancelled

### ISSUE THREAD

**Issue by gebner** [actions/upload-artifact#256]
**Describe the bug**
The action sometimes creates a `/tmp/tmp-*` file without deleting it.  After a few days, our self-hosted runners then run out of disk space.

```
$ ls -lhStr /tmp/tmp-*
-rw------- 1 ghrunner ghrunner 375M Oct 11 18:48 /tmp/tmp-1073567jSpOcX6hU3t
-rw------- 1 ghrunner ghrunner 377M Oct 12 08:21 /tmp/tmp-184654aEgLVcTxJdgo
-rw------- 1 ghrunner ghrunner 374M Oct 12 15:05 /tmp/tmp-219373x67k3vOOr2Kv
-rw------- 1 ghrunner ghrunner 385M Oct 12 17:59 /tmp/tmp-242609uUbATNlg48KV
-rw------- 1 ghrunner ghrunner 381M Oct 13 04:34 /tmp/tmp-303693s5foRET1p750
```

I am not 100% certain that these are created by the upload-artifact action, but they are binary files compressed using gzip, contain the artifact we are uploading, the creation time corresponds with the time the action was invoked, and the file names follow the naming scheme used here:
https://github.com/actions/upload-artifact/blob/11e311c8b504ea40cbed20583a64d75b4735cff3/dist/index.js#L1870-L1878

**Version**
- [ ] V1
- [x] V2

**Environment**
- [x] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**

For reference, this is the workflow file: https://github.com/leanprover-community/mathlib/blob/ea70e1c06e6ca0d14a91721ad5a9f96ac59d309c/.github/workflows/build.yml

This is the worker log file for the run which I suspect created the last temporary file:
https://gist.github.com/gebner/a41508719c5b6713a4abe23ba9fc9028

Link to the run on github actions:
https://github.com/leanprover-community/mathlib/runs/3878471017?check_suite_focus=true

**Comment by konradpabjan** [comment]
v4 has shipped officially today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over!

One of the improvements/changes we made was that now during upload there are no temporary files created. Everything is handled using streams so post upload or in the event of a failure or cancellation there should be no temporary files left on any runner.
