### ISSUE TITLE
File size of uploaded artifacts shows up uncompressed

### ISSUE THREAD

**Issue by Tyrrrz** [actions/upload-artifact#26]
Not sure if this is an appropriate place for this issue, but basically once you upload an artifact with this action, it will appear in the artifacts list. The problem is that it shows the file size uncompressed, despite being packed in an archive.

**Comment by joshmgross** [comment]
@Tyrrrz This is intentional. The file size represents the size uploaded, not the size compressed.

**Comment by Tyrrrz** [comment]
Would it be possible to at least show both? This is a bit confusing.

**Comment by leecbaker** [comment]
Which size is used for billing? It should probably clear which is used.

**Comment by tovbinm** [comment]
@leecbaker good point. Which one it is? I started upload code coverage artifacts on each build and got to 2gb in less than a week! Compressed file 1.6mb and uncompressed 26mb.

**Comment by joshmgross** [comment]
The docs have been updated to clarify this:

>Artifacts are uploaded during a workflow run, and you can view an artifact's name and size in the UI. When an artifact is downloaded using the GitHub UI, all files that were individually uploaded as part of the artifact get zipped together into a single file. This means that billing is calculated based on the size of the uploaded artifact and not the size of the zip file.

https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
