### ISSUE TITLE
uploaded assets only served with content-type=application/octet-stream even if, e.g. image/png specified

### ISSUE THREAD

**Issue by slayoo** [actions/upload-artifact#260]
As discussed earlier today here:
- https://github.com/pypa/warehouse/issues/10234
- https://github.com/eine/tip/issues/161

artefacts uploaded for releases are only served with content-type=application/octet-stream even if the actual content is of image type, for instance. In the case of images it makes the pypi.org image proxy report 404 for existing images. Is it possible to get these assets with the actual content-type somehow?

Example asset: https://api.github.com/repos/atmos-cloud-sim-uj/PySDM/releases/assets/47669054

Getting it through the browser_download_url results in "save-as" dialog, and the above-mentioned 404 in case of pypi.org image proxy.

Help welcome, thanks!
Sylwester

**Comment by konradpabjan** [comment]
So artifacts creating by actions are not the same thing as assets uploaded as part of releases (artifacts is used interchangeably here) and they fundamentally server a different purpose.

Some more information about artifacts here: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts

Some information about releases: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

---

When uploading artifacts as part of a release, we had a first party actions to support this but we stopped maintaining it: https://github.com/actions/upload-release-asset

There is some information in that archived repository about potential issues and actions that are maintained to support uploading release assets so I recommend looking at that.
