### ISSUE TITLE
Artifacts URL not showing up

### ISSUE THREAD

**Issue by FezVrasta** [actions/upload-artifact#261]
**Describe the bug**
Some times after the artifacts job completes successfully, the link to download the artifacts is not displayed on the run page.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

![CleanShot 2021-10-26 at 14 52 59@2x](https://user-images.githubusercontent.com/5382443/138882763-e3ca8c3c-ae8f-4d42-aaa4-4600d0c4c30d.jpg)

**Run/Repo Url**
Private repo.

**How to reproduce**
Not sure.

**Additional context**
N/A

**Comment by francescov1** [comment]
+1

**Comment by JamesBurnside** [comment]
Also seeing this issue; we can no longer see it in the spot highlighted in this issue, however for us, we can still see them in the action summary page:
![image](https://user-images.githubusercontent.com/2684369/141597362-7e6bd0e2-0eda-4a69-b77f-f2e288ddad34.png)
![image](https://user-images.githubusercontent.com/2684369/141597383-d518a7e1-0a0c-4bff-b0eb-e4af2d74caba.png)

example run: https://github.com/Azure/communication-ui-library/runs/4195569375?check_suite_focus=true

**Comment by robherley** [comment]
👋 This is intentional by design. The UI that @JamesBurnside pointed out is the correct entry point to retrieve artifacts across your jobs for that workflow run. The old artifacts dropdown that you are looking for is part of the legacy UI.

**Comment by FezVrasta** [comment]
Thanks for the reply. Could you describe the shorter amount of clicks required to get to that screen? Right now the only way I found is to go to the page where all the runs are listed and click on the right one
