### ISSUE TITLE
Access denied trying to upload a file despite giving it full permissions.

### ISSUE THREAD

**Issue by jamesNWT** [actions/upload-artifact#267]
**Describe the bug**
I am making an action that runs API tests from a docker container, which generates a .html file report. I save the report to a volume. Then, in the action's .yml I use upload artifact wit the volume's location on the host. (/var/lib/docker/volumes/.../report.html). The problem is I get `Error: EACCES: permission denied, lstat /var/lib/docker/volumes/.../report.html` when the action attempts to do this.

The docker container is run via docker-composing from the action.  

I've tried to solve this by doing `sudo chmod ugo+rwx /var/lib/docker/volumes/.../report.html`  before using the action but it changed nothing. I think running the action with sudo would work but that doesn't seem to be supported.

This is probably more of a knowledge gap than a bug, but help would be greatly appreciated. 

**Version**
- [ ] V1
- [X] V2

**Environment**
- [ ] self-hosted
- [X] Linux
- [ ] Windows
- [ ] Mac

**How to reproduce**
I've made a minimum example that exactly reproduces my behavior here: https://github.com/jamesNWT/example

**Comment by jamesNWT** [comment]
Haven't solved this, I don't think this belongs here.

**Comment by penguin359** [comment]
One of the parent folders is likely not allowed. Every folder down that path could block access to that file depending on the permissions set. It might be simpler to copy the file out to a known good location first and then upload that.

**Comment by jamesNWT** [comment]
> One of the parent folders is likely not allowed. Every folder down that path could block access to that file depending on the permissions set. It might be simpler to copy the file out to a known good location first and then upload that.

I forgot about this, but I solved the problem. Here is the stackoverflow page which has the solution: https://stackoverflow.com/questions/69977574/github-actions-upload-artifact-access-denied-trying-to-upload-a-file-despite
