### ISSUE TITLE
[bug] Error: No uploaded artifact was found!

### ISSUE THREAD

**Issue by brian6484** [actions/upload-artifact#287]
### What happened?

Hello guys. I tried using a Jekyll theme for my github page.
However, as I was committing and pushing my changes, there was this sudden error that  Github Build and Deploy Error: No uploaded artifact was found.
I am not even sure what artifact was and how it is being used in my github page.
If you have come across this issue and know a solution, please let me know.
My environment workflow is https://github.com/brian6484/brian6484.github.io/deployments

Thank you.

p.s. I'm not sure if this helps but when I deployed my github page with jekyll theme, I received 4 notification emails from dependabot.
It asked me to update rake requirement, jekyll-feed requirement, jekyll-seo-tag requirement and bump tzinfo.
Like for example:
c940b3a Update jekyll-seo-tag requirement from ~> 2.6.1 to >= 2.6.1, < 2.8.0
But I didnt know how to update the requirements so I just ignored them since my github page can do commits and pushes.
But now it cannot, so yea :(

### What did you expect to happen?

Commits and pushes should work normally but they don't

### How can we reproduce it?

https://github.com/brian6484/brian6484.github.io

### What version of the action are you using?

not sure

### What are your runner environments?

window

**Comment by adri-MASH** [comment]
I ran into the same problem by committing some changes to the config file today.

**Comment by hridaydutta123** [comment]
@brian6484 Is this solved? I am still facing the artifact issue on GitHub pages.

**Comment by hridaydutta123** [comment]
Realized this issue occurs when there is an empty submodule in your GitHub repo. Removed the empty submodule and its working now.

**Comment by abubelinha** [comment]
@hridaydutta123 what is an empty submodule?  An empty folder?

**Comment by hridaydutta123** [comment]
@abubelinha in my case, it was an empty folder with .git pointing to another repository.

**Comment by UjjwalSaini07** [comment]
I also face This same issue 
Error: No uploaded artifact was found! Please check if there are any errors at build step.
What should i do now. Please anyone help Me in that.

![issue1](https://user-images.githubusercontent.com/73696489/154907036-67aa0f01-a8eb-4e11-a69e-de6869993f08.PNG)

**Comment by jung-youjin** [comment]
@UjjwalSaini07 Getting the same error as well. Have you solved this issue? :'(

**Comment by UjjwalSaini07** [comment]
@jung-youjin **_My error Solved and Fixed..._**
regards__

**Comment by naniferra** [comment]
@UjjwalSaini07 Hello! I have the same error, could you tell me how you solved it? thank you so much!

![Captura de pantalla 2023-07-06 194421](https://github.com/actions/upload-artifact/assets/131623318/7b1665b5-8e2d-48dc-a0c9-8a0d131a9177)
