### ISSUE TITLE
Create Artifact Container - Attempt 5 of 5 failed with error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by nibanks** [actions/upload-artifact#292]
### What happened?

A couple times a week, I see this failure in our GitHub Actions when trying to upload results. For instance:

https://github.com/microsoft/msquic/runs/5039457590?check_suite_focus=true
```
Artifact name is valid!
Create Artifact Container - Attempt 1 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Create Artifact Container - Attempt 2 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Create Artifact Container - Attempt 3 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Create Artifact Container - Attempt 4 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Create Artifact Container - Attempt 5 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Error: Create Artifact Container failed: connect ETIMEDOUT 13.107.42.16:443
```

### What did you expect to happen?

The artifact to be successfully uploaded.

### How can we reproduce it?

This GitHub action occasionally repro's it: https://github.com/microsoft/msquic/actions/workflows/wan-perf.yml

### Anything else we need to know?

Our action runs a lot of parallel jobs that might be making the issue worse.

### What version of the action are you using?

actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2

### What are your runner environments?

window

**Comment by nibanks** [comment]
Another instance: https://github.com/microsoft/msquic/runs/5067902189?check_suite_focus=true

**Comment by Slach** [comment]
I see same situation too
https://github.com/AlexAkulov/clickhouse-backup/runs/5089647848?check_suite_focus=true

**Comment by yatima1460** [comment]
Can confirm, same problem

Error: connect ETIMEDOUT 13.107.42.16:443

**Comment by nibanks** [comment]
Our pipeline continues to hit these issues in just one or two jobs every time, invalidating the whole thing. Who can take a look at this please?

**Comment by guruprasadsingirikonda** [comment]
> I am seeing the same ![image](https://user-images.githubusercontent.com/10775043/153596152-b96209f0-7a21-46a1-9888-4c381c213646.png) @konradpabjan is this related to your fix in january?

did this resolved?

**Comment by rgajason** [comment]
I have a similar issue that occurs when trying to register a new runner.  I get SSL timeout errors and it always leads back to 13.107.42.16:443.  Note that that address is not included in the GH meta information: https://api.github.com/meta

**Comment by konradpabjan** [comment]
A lot of these timeouts are transient. Sometimes Azure would have issues for a very small percentage of requests. 

Anyway, today we released a new v4 `upload-artifact` today! Recommend switching over.

https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

v4 is a complete rewrite of the artifact actions with a new backend. v4 is all around more reliable, simpler and a host and these types of connection timeouts should no longer happen as the upload flow is totally different.

If there are any similar issues with v4 then please open up new issues
