### ISSUE TITLE
[bug] Error: UNKNOWN: unknown error, stat 'D:\a\ansible-lint\ansible-lint\.tox\py39-ansible29\bin\python'

### ISSUE THREAD

**Issue by ssbarnea** [actions/upload-artifact#295]
### What happened?

Apparently when trying to archive some logs that were created with tox under WSL, the `actions/upload-artifact@v2` can produce a very weird error:

```
Run actions/upload-artifact@v2
  with:
    name: logs.zip
    path: .tox/**/log/
    if-no-files-found: warn
  env:
    TOX_PARALLEL_NO_SPINNER: 1
    FORCE_COLOR: 1
    WSLENV: FORCE_COLOR:TOXENV:TOX_PARALLEL_NO_SPINNER
Error: UNKNOWN: unknown error, stat 'D:\a\ansible-lint\ansible-lint\.tox\py39-ansible29\bin\python'
```

This can be seen only on the Windows runner, https://github.com/ansible-community/ansible-lint/runs/5139818295?check_suite_focus=true#step:15:10

The biggest problem is that this is eminting an error-annotation which gets exposed into workflow summary page, and there is nothing we can do to silence it.

### What did you expect to happen?

No error?

### How can we reproduce it?

https://github.com/ansible-community/ansible-lint/runs/5139818295?check_suite_focus=true#step:15:10 -- it does reproduce consistently.

If really needed, we should be able to create a simple workflow that does produce a similar error.

### Anything else we need to know?

I suspect that this has to do with some file-system relating things related to WSL.

That file in particular is a symlink and apparently this action chokes when it encounters them instead of ignoring them.

### What version of the action are you using?

v2

### What are your runner environments?

window

**Comment by konradpabjan** [comment]
This looks like a repeat of https://github.com/actions/upload-artifact/issues/324 or at least pretty similar to the issue

This should now be resolved. V4 just dropped so I recommend switching over: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

V4 no longer relies on the `stat` command in any way so there is no way this error can happen again
