### ISSUE TITLE
[bug] Cannot upload artifact from /var/folders on Mac OS

### ISSUE THREAD

**Issue by apupier** [actions/upload-artifact#299]
### What happened?

On MacOS, the temporary folder cannot be accessed to upload artifact.
There is this kind of error:
`EPERM: operation not permitted, stat '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/0/SafariFamily'`

### What did you expect to happen?

I expect that all files can be potentially archived

### How can we reproduce it?

https://github.com/camel-tooling/camel-lsp-client-vscode/runs/5232448585?check_suite_focus=true#step:12:12

### Anything else we need to know?

I tried to set the folder as reabable in a previous step without success https://github.com/camel-tooling/camel-lsp-client-vscode/runs/5232875386?check_suite_focus=true#step:12:1

### What version of the action are you using?

v2

### What are your runner environments?

macos

**Comment by konradpabjan** [comment]
V4 just dropped and I recommend switching over: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

V4 does not use any temporary files during upload (unlike earlier versions) and it no longer uses to `stat` command as well to get certain file information

A few similar issues were closed out as well such as https://github.com/actions/upload-artifact/issues/130#issuecomment-1857891171
