### ISSUE TITLE
[bug] Error: EPERM: operation not permitted, stat D:\a\<something>

### ISSUE THREAD

**Issue by kumaakh** [actions/upload-artifact#324]
### What happened?

We use upload artifacts action to upload build logs from failed builds. The builds run on GH hosted runners. The upload task fails on windows for some files with the following error:

Error: EPERM: operation not permitted, stat 'D:\a\ApraPipes\ApraPipes\build\vcpkg_installed\x64-windows\tools\meson\test cases\frameworks\35 boost symlinks\boost\include\boost'
I suspect that the failure is due to spaces in the file name ? but that is anyone's guess.

The main point of this issue is that an upload task should never fail due to one file producing an error, it should upload the rest and generate warnings. 

Like in this case our ability to debug the build failure is hampred as the logs are not getting uploaded due to this action failing

see https://github.com/Apra-Labs/ApraPipes/runs/6333795173?check_suite_focus=true#step:15:100

### What did you expect to happen?

The upload task should never fail due to one file producing an error, it should upload the rest and generate warnings. 
also such errors should be handled. 
e.g. in this case we have no control over the GH runner environment

### How can we reproduce it?

Fork from https://github.com/Apra-Labs/ApraPipes and run github action on https://github.com/Apra-Labs/ApraPipes/blob/main/.github/workflows/CI.yml, with just the 'windows-2019' from matrix

The build will fail and also the upload build logs atsk will also fail

### Anything else we need to know?

This is a windows specific issue

### What version of the action are you using?

v2 and v3

### What are your runner environments?

window

**Comment by kumaakh** [comment]
[build-log.txt](https://github.com/actions/upload-artifact/files/8645913/build-log.txt)

added the full build log

**Comment by horror-proton** [comment]
I ran into the same error :thinking:

> EPERM: operation not permitted, stat 'D:\a\MaaDeps\MaaDeps\vcpkg\buildtrees\flatbuffers\src\90ca59e5af-4f492a528d.clean\java\src\test\java\DictionaryLookup'

**Comment by konradpabjan** [comment]
This should now be resolved. V4 just dropped so I recommend switching over: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

V4 no longer relied on `stat` so there should no longer be permission issues. If anyone can confirm then we can close this out. There were a few similar issues that we were able to close out such as https://github.com/actions/upload-artifact/issues/130#issuecomment-1857891171
