### ISSUE TITLE
This is annoying.

### ISSUE THREAD

**Issue by Joalor64GH** [actions/upload-artifact#336]
### What happened?

I got this error.
No files were found with the provided path: export/release/windows/bin. No artifacts will be uploaded.
How do I fix it?

### What did you expect to happen?

Get an artifact.

### How can we reproduce it?

Idk what this means.

### What version of the action are you using?

v2.2.4

### What are your runner environments?

window

**Comment by iamludal** [comment]
The error message is pretty explicit: the files you are trying to upload simply don't exist. Can you try to run `tree` to reveal the folder structure?
