### ISSUE TITLE
[bug] 400 Bad Request

### ISSUE THREAD

**Issue by jadamcrain** [actions/upload-artifact#343]
### What happened?

Getting a 400 bad request when uploading artifact with v2 or v3 of `actions/upload-artifact`.

### What did you expect to happen?

The upload to succeed

### How can we reproduce it?

https://pipelines.actions.githubusercontent.com/SmQwXEh0cFbDQzjZXhuIqcgDUADQmdE2MLnXHEirXHTTDJYhQP/_apis/resources/Containers/18215619?itemPath=ffi-modules%5Ci686-pc-windows-msvc

Strangely this is happening in a matrix:

https://github.com/stepfunc/rodbus/blob/refactor/optional-deps/.github/workflows/ci.yml#L128

I can't see how this artifact upload 

### What version of the action are you using?

v2 and v3

### What are your runner environments?

window

**Comment by konradpabjan** [comment]
V4 upload-artifact has released today! Recommend switching over.

https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

v4 is a complete rewrite of the artifact actions with a new backend. v1-v3 uploads sometimes would hit transient errors like 500s or 400s that you see. v4 is all around more reliable, simpler and a host of issues described in this issue should no longer happen.

If there are any similar issues with v4 then please open up new issues
