### ISSUE TITLE
[bug] artifact upload stopped working

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [actions/upload-artifact#345]
### What happened?

after successful build of my project the artifacts should be uploaded, but since today all uploads fail:

The least common ancestor is /home/runner/work/bobbycar-boardcomputer-firmware/bobbycar-boardcomputer-firmware/repository/build_allfeatures. This will be the root directory of the artifact
With the provided path, there will be 2 files uploaded
Create Artifact Container - Error is not retryable
##### Begin Diagnostic HTTP information #####
Status Code: 403
Status Message: Forbidden
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "333",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "b4816d4e-2d4c-4e4a-9d82-70725bf1f729",
  "activityid": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-tfs-session": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-vss-e2eid": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-vss-senderdeploymentid": "f7faf8cf-7ae4-3f62-0792-ce64b15bce23",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 3828FE4BC5DF4E31A6F0FB7D21[19](https://github.com/0xFEEDC0DE64/bobbycar-boardcomputer-firmware/runs/8259940443?check_suite_focus=true#step:17:20)9836 Ref B: BN3EDGE0716 Ref C: 2022-09-08T22:35:16Z",
  "date": "Thu, 08 Sep 2022 22:35:16 GMT",
  "connection": "close"
}
##### Begin Diagnostic HTTP information #####
Status Code: 403
Status Message: Forbidden
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "333",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=259[20](https://github.com/0xFEEDC0DE64/bobbycar-boardcomputer-firmware/runs/8259940443?check_suite_focus=true#step:17:21)00",
  "x-tfs-processid": "b4816d4e-2d4c-4e4a-9d82-70725bf1f729",
  "activityid": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-tfs-session": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-vss-e2eid": "e359c5ee-ed97-4259-be4f-c9da1c67f4c0",
  "x-vss-senderdeploymentid": "f7faf8cf-7ae4-3f62-0792-ce64b15bce23",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 3828FE4BC5DF4E31A6F0FB7D[21](https://github.com/0xFEEDC0DE64/bobbycar-boardcomputer-firmware/runs/8259940443?check_suite_focus=true#step:17:22)199836 Ref B: BN3EDGE0716 Ref C: 20[22](https://github.com/0xFEEDC0DE64/bobbycar-boardcomputer-firmware/runs/8259940443?check_suite_focus=true#step:17:23)-09-08T22:[35](https://github.com/0xFEEDC0DE64/bobbycar-boardcomputer-firmware/runs/8259940443?check_suite_focus=true#step:17:36):16Z",
  "date": "Thu, 08 Sep 2022 22:35:16 GMT",
  "connection": "close"
}
### What did you expect to happen?

The upload works as usual

### How can we reproduce it?

I dont know, maybe by forking my repo and testing the CI there again?

### What version of the action are you using?

2.2.4

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
v4 has shipped today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

I recommend switching over as these classes of issues should no longer happen with the release
