### ISSUE TITLE
[bug] idk

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [actions/upload-artifact#347]
### What happened?

With the provided path, there will be 669 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Create Artifact Container - Error is not retryable
##### Begin Diagnostic HTTP information #####
Status Code: 403
Status Message: Forbidden
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "333",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "92e14b82-96eb-4134-85a8-8fff4eead2[11](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:12)",
  "activityid": "4cb0692c-c206-4f26-9b7c-78[12](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:13)b67b5c6b",
  "x-tfs-session": "4cb0692c-c206-4f26-9b7c-7812b67b5c6b",
  "x-vss-e2eid": "4cb0692c-c206-4f26-9b7c-7812b67b5c6b",
  "x-vss-senderdeploymentid": "f7faf8cf-7ae4-3f62-0792-ce64b15bce23",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 3D2F9232F24B4941B467D146CDEA5217 Ref B: BL2AA2030106011 Ref C: 2022-09-17T07:38:24Z",
  "date": "Sat, 17 Sep 2022 07:38:24 GMT",
  "connection": "close"
}
##### Begin Diagnostic HTTP information #####
Status Code: 403
Status Message: Forbidden
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "333",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "92e14b82-96eb-4[13](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:14)4-85a8-8fff4eead211",
  "activityid": "4cb0692c-c206-4f26-9b7c-7812b67b5c6b",
  "x-tfs-session": "4cb0692c-c206-4f26-9b7c-7812b67b5c6b",
  "x-vss-e2eid": "4cb0692c-c206-4f26-9b7c-7812b67b5c6b",
  "x-vss-senderdeploymentid": "f7faf8cf-7ae4-3f62-0792-ce64b15bce23",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: 3D2F9232F24B4941B467D[14](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:15)6CDEA52[17](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:18) Ref B: BL2AA[20](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:21)30106011 Ref C: 20[22](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:23)-09-17T07:38:[24](https://github.com/LEVIXDDLMAO/Indie_Cross_v4/actions/runs/3072561458/jobs/4964131574#step:7:25)Z",
  "date": "Sat, 17 Sep 2022 07:38:24 GMT",
  "connection": "close"
}
### What did you expect to happen?

it to upload all my files

### How can we reproduce it?

i dont think so

### Anything else we need to know?

nope

### What version of the action are you using?

idk

### What are your runner environments?

window

### Are you on GitHub Enterprise Server? If so, what version?

idk

**Comment by konradpabjan** [comment]
v4 shipped today https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over as this type of issue no longer happens
