### ISSUE TITLE
upload of artifacts randomly fail

### ISSUE THREAD

**Issue by Disservin** [actions/upload-artifact#360]
### What happened?

This Action was run twice. First attempt the artifact upload for `Windows 2022 Mingw-w64 Clang x86_64` failed and `MacOS 12 Apple Clang` was successful. Second attempt `MacOS 12 Apple Clang` failed to upload.
https://github.com/Disservin/Stockfish/actions/runs/3397756292/attempts/1

There was one commit that had a successful Action but it failed to upload on the second attempt.
https://github.com/Disservin/Stockfish/actions/runs/3397492985

The error doesnt help me much either
`Unexpected response. Unable to upload chunk to https://pipelines.actions.githubusercontent.com/I9cMmMHfx8HvRgYy9gJYarpnO4xiF8KsZmuFn7sqlM17oeIQjg/_apis/resources/Containers/2314699?itemPath=Stockfish+Binaries+windows-2022%5Cstockfish-x86-64-avx512-windows-2022.exe`

### What did you expect to happen?

I expected a successful upload of the artifact.

### How can we reproduce it?

Currently I dont know, I suspect it has something to do with the size of the upload or how many files where uploaded.

https://github.com/Disservin/Stockfish
https://github.com/Disservin/Stockfish/actions

### What version of the action are you using?

v3

### What are your runner environments?

linux, window, macos

**Comment by konradpabjan** [comment]
v4 has been released today which is a complete rewrite of v1-v3 where this error was occurring: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4 today! Uploads are much more reliable and this class of issues doesn't happen anymore
