### ISSUE TITLE
[feat req] - Ability to disable compression

### ISSUE THREAD

**Issue by todaywasawesome** [actions/upload-artifact#367]
### What would you like to be added?

Add a flag for disabling compression before uploading. 

### Why is this needed?

For some workloads the compression takes significantly longer than the time to just upload directly. Also if an artifact is already compressed there doesn't seem to be a way to specify to skip additional compression. The end result is this step runs slower than it needs to in many cases.

**Comment by mattgodbolt** [comment]
Related to #199.

**Comment by konradpabjan** [comment]
V4 upload-artifact was released today: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

With it comes a new `compression-level` input
https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size

Users can now play around with various levels and even select `0` to disable it entirely. `0` still packages a `.zip` file (we need everything in a zip for consistency and future UI updates and improvements) and that behavior is not going to change but certain already compressed uploads with v4 and a `compression-level` of `0` are 98% faster from our testing.

Recommend switching to v4! 😃

**Comment by luisherranz** [comment]
> still packages a .zip file (we need everything in a zip for consistency and future UI updates and improvements) and that behavior is not going to change

Can't you detect if the file you are zipping is already a zip, and if it is, avoid zipping it again? A double-zipped file doesn't have any benefits.

**Comment by orz12** [comment]
> V4 upload-artifact was released today: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
> 
> With it comes a new `compression-level` input https://github.com/actions/upload-artifact?tab=readme-ov-file#altering-compressions-level-speed-v-size
> 
> Users can now play around with various levels and even select `0` to disable it entirely. `0` still packages a `.zip` file (we need everything in a zip for consistency and future UI updates and improvements) and that behavior is not going to change but certain already compressed uploads with v4 and a `compression-level` of `0` are 98% faster from our testing.
> 
> Recommend switching to v4! 😃

need a way to disable zip totally🙊

**Comment by mike-gorman-quest** [comment]
It is annoying to constantly have to unzip ZIP files that are downloaded when "downloading artifacts" is a routine part of one's workflow.  Request that `compression-level=0` to mean "do not compress at all, upload the raw artifact as-is without any ZIP extension."

**Comment by tonyhutter** [comment]
> Request that compression-level=0 to mean "do not compress at all, upload the raw artifact as-is without any ZIP extension."

I'll 2nd this.  One of our artifacts is a small text file, and it's burdensome to have to unzip it rather than just clicking on it and opening it in a new tab.

**Comment by adriendupuis** [comment]
Or, at least, allow to attach file to comment created from action.

**Comment by sean-rose** [comment]
https://github.blog/changelog/2026-02-26-github-actions-now-supports-uploading-and-downloading-non-zipped-artifacts/
