### ISSUE TITLE
"You've used 100% of included services for GitHub Storage (GitHub Actions and Packages)"

### ISSUE THREAD

**Issue by varndellwagglebee** [actions/upload-artifact#385]
### What happened?

Getting "You've used 100% of included services for GitHub Storage (GitHub Actions and Packages)" after deleting all Artifacts?  I have deleted and waited over two days to see if it clears.

### What did you expect to happen?

Clear the message

### How can we reproduce it?

Hit the max for storage and delete artifacts

### What version of the action are you using?

none

### What are your runner environments?

linux

**Comment by Vazno** [comment]
#161

**Comment by SrRyan** [comment]
https://github.com/actions/upload-artifact/issues/161#issuecomment-1836491917
