### ISSUE TITLE
[bug]No Artifacts in UI show Although log shows that Artifacts has been uploaded successfully

### ISSUE THREAD

**Issue by Abirdcfly** [actions/upload-artifact#389]
### What happened?

github action log shows that Artifacts has been uploaded successfully, but UI show nothing.

github action is this https://github.com/bestchains/fabric-operator/actions/runs/4193043025/attempts/5

![CleanShot 2023-02-17 at 10 03 20](https://user-images.githubusercontent.com/5100555/219530737-2ec45c14-ce02-4155-8f74-9ba76670a9e4.png)

And github log show:
https://github.com/bestchains/fabric-operator/actions/runs/4193043025/jobs/7283530966#step:7:23
![CleanShot 2023-02-17 at 10 04 10](https://user-images.githubusercontent.com/5100555/219530862-7f297017-a4ab-43a8-a295-30ff1cffd160.png)

### What did you expect to happen?

show artifacts uri in UI

### How can we reproduce it?

no idea.

### Anything else we need to know?

Maybe bugs are not here with actions/upload-artifact, so the same bug is also reported to comunity: https://github.com/community/community/discussions/47721.

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by tlevesque-ueat** [comment]
We've seen this as well, in a build 3 days ago.
The logs show that the artifact were successfully uploaded, but they don't appear in the UI.
Another workflow that tried to download these artifacts failed with the following error:
```
Run dawidd6/action-download-artifact@v2
==> Repository: <redacted>
==> Artifact name: dist
==> Local path: ./packages
==> Workflow name: .github/workflows/<redacted>
==> Workflow conclusion: success
==> Commit: <redacted>
==> (found) Run ID: 4[28](https://github.com/<redacted>#step:7:29)69472[31](https://github.com/<redacted>#step:7:32)
==> (found) Run date: 2023-02-27T21:21:24Z
==> (not found) Artifact: dist
==> Found the following artifacts instead:
Error: no artifacts found
```

**Comment by boweiliu** [comment]
Hi, just sharing, i'm having this issue as well

**Comment by boweiliu** [comment]
```
Run actions/upload-artifact@v3
With the provided path, there will be 10 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "e2e-videos" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 5040425 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 5323198 bytes
The size of all the files that were uploaded is 5040425 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Artifact e2e-videos has been successfully uploaded!
```
<img width="404" alt="Screen Shot 2023-04-12 at 1 41 18 PM" src="https://user-images.githubusercontent.com/15707615/231579772-cce8a069-a509-4582-aab9-27bf7855158a.png">

**Comment by maxisam** [comment]
> We've seen this as well, in a build 3 days ago. The logs show that the artifact were successfully uploaded, but they don't appear in the UI. Another workflow that tried to download these artifacts failed with the following error:
> 
> ```
> Run dawidd6/action-download-artifact@v2
> ==> Repository: <redacted>
> ==> Artifact name: dist
> ==> Local path: ./packages
> ==> Workflow name: .github/workflows/<redacted>
> ==> Workflow conclusion: success
> ==> Commit: <redacted>
> ==> (found) Run ID: 4[28](https://github.com/<redacted>#step:7:29)69472[31](https://github.com/<redacted>#step:7:32)
> ==> (found) Run date: 2023-02-27T21:21:24Z
> ==> (not found) Artifact: dist
> ==> Found the following artifacts instead:
> Error: no artifacts found
> ```

We just had this issue, but the job in the same workflow can download it just fine. However, I can't find it anywhere on UI

**Comment by rtibbles** [comment]
This has just happened to us in this job: https://github.com/learningequality/kolibri/actions/runs/5378800426 - jobs reliant on the artifacts are able to download and use them, but none of them are showing up in the UI.

**Comment by josegonzalez** [comment]
I've noticed that artifacts aren't available via API until the workflow completes (though the actions/download-artifact still works for me somehow).

**Comment by Jayjay1488** [comment]
I just need help I sent money for a lot of the stuff and didn't receive it got

**Comment by nicolasconnault** [comment]
Same issue here. I might try using the Github API to find them
https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

**Comment by nikolaiessel** [comment]
This happens for me when using environments containing assigned reviewers. The situation is somewhat the same as mentioned in another issue: https://github.com/actions/upload-artifact/issues/53#issuecomment-844674400

Our artifacts must be deployed manually and will be "approved", when the responsible person has done his job. But because the Artifacts List is not shown, the deployment cannot be done.

Current workaround: cancelling the workflow, download the appearing artifacts, then re-run all "failed" jobs

**Comment by konradpabjan** [comment]
v4 upload-artifact has been released today: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

v4 is a complete rewrite of v1-v3 with a new architecture and the limitations described in this issue are no longer there. Immediately after a step uploads an artifact there is an artifact ID that can be used to interact with all our APIs. Also artifact sshow up in the UI immediately and can be downloaded while the main run is still in progress. This is very useful for things like environments/gates/approvals where you can download and inspect an artifact before approving. 

Recommend switching to v4 today! 😃

**Comment by SunStupic** [comment]
> I'm facing the same issue!

Remember to click on left side first and then scroll down.

<img width="1579" alt="image" src="https://github.com/actions/upload-artifact/assets/90165041/8a6680b0-15fe-43fc-ba62-c28059df6f6c">

**Comment by ebalodis** [comment]
We still see this issue in our workflows. Using v4 upload artifact action.

**Comment by Architrixs** [comment]
> We still see this issue in our workflows. Using v4 upload artifact action.

+1
found any solution?

**Comment by ebalodis** [comment]
> > We still see this issue in our workflows. Using v4 upload artifact action.
> 
> +1 found any solution?

Nope

**Comment by workerbee22** [comment]
Still an issue !!!

**Comment by workerbee22** [comment]
Not resolved so why closed?

**Comment by mhyassin** [comment]
Still an issue

**Comment by jesseadams** [comment]
@konradpabjan Still an issue!

**Comment by mattculler** [comment]
We've just seen this issue as well.  Unfortunately it's on a private repo, but it's as described earlier - using upload-artifact v4, upload reported successful, can download via URL, but the artifact doesn't show on the main page where it normally would.
