### ISSUE TITLE
How to specify the path

### ISSUE THREAD

**Issue by bugproof** [actions/upload-artifact#40]
I have files in  /home/runner/work/.../src/MyProject/bin/Release ... I tried copying this path but I get an error:

```
##[error]Value cannot be null. (Parameter 'name')
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.162.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by konradpabjan** [comment]
The error message indicates you are missing the `name` parameter (see the examples in the README). You have to specify this when uploading an artifact. Later when you are using the `download-artifact` action, you use the same name to specify what you want to download it.
