### ISSUE TITLE
[bug] Upload speeds are abysmal

### ISSUE THREAD

**Issue by StephenHodgson** [actions/upload-artifact#403]
### What happened?

I have a self hosted machine with a 5 gbps connection. Uploading a ~2.5gb zipped file still takes upwards of 10 min. 

```markdown
The raw size of all the files that were specified for upload is 906151850 bytes
Upload time 4 m 16s
```

### What did you expect to happen?

Faster upload speeds that should scale with infrastructure.

### How can we reproduce it?

unsure. 

### What version of the action are you using?

v3.1.2

### What are your runner environments?

self-hosted

**Comment by Jayjay1488** [comment]
I need help with this please email me jamiechimileski19@gmail.com

**Comment by IsaiahSchultzTR** [comment]
+1

**Comment by StephenHodgson** [comment]
> See: #199

Not really related as 199 is talking about zipping files and then performing upload. This is purely about upload speed bottlenecks by the hosted infrastructure on GitHub/Azure side.

**Comment by nbarbettini** [comment]
> upload speed bottlenecks by the hosted infrastructure on GitHub/Azure side

To my understanding that is what #199 is about too. There is a long discussion of workarounds (including zipping), but the core reported issue is "uploading is very slow".

**Comment by screig** [comment]
365mb of data

![image](https://github.com/actions/upload-artifact/assets/4292074/51ab3c50-d827-409d-a343-4d088aac6fcf)

after 10mins

![image](https://github.com/actions/upload-artifact/assets/4292074/fdd45f9f-7bbb-4d5a-969d-8562c5a6baa1)

it has done 70%
 
![image](https://github.com/actions/upload-artifact/assets/4292074/cc5a636b-c5f1-47d3-897c-69a333731e8e)

- Can someone explain why this is so slow? 
- How long should I allow for uploading ~400mb of data, half an hour?

**Comment by ArunJRK** [comment]
It is taking 3 to 4hrs to deploy a project 😢

**Comment by fanyanjie-pacvue** [comment]
750MB file take 252s, it's only 3MB/s 😭

**Comment by namanrawal47** [comment]
A 2.8 MB file is taking 12 minutes to upload on Github Enterprise.

**Comment by StephenHodgson** [comment]
Bippity bummpity boop

**Comment by StephenHodgson** [comment]
Found the source of the problem. It seems that the uploads are artificially bottlenecked by the zip chunk processing, which is limited to 8 MB per cycle.

I'm not sure why this was specific value was chosen but imho it should be dynamically calculated or completely removed.

**Comment by StephenHodgson** [comment]
Almost 6 months and no direct reply from @github. Starting to feel like GitHub actions isn't under active development, or they make a lot of extra $$$ keeping this slow and and charging us for extra cycles.

**Comment by jeansilvapbfy** [comment]
Any update on this?

**Comment by madhusameena** [comment]
Any update or workaround please?

**Comment by prplecake** [comment]
I would assume GitHub is financially stable enough to afford better upload speeds than I get at home.

**Comment by StephenHodgson** [comment]
v4 def sees a HUGE increase in perf. Thanks Team!
