### ISSUE TITLE
/__e/node16/bin/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zopolis4** [actions/upload-artifact#409]
### What happened?

When attempting to run the action within a docker container (satmandu/crewbuild:amd64), uploads fail like so:
```
Run actions/upload-artifact@v3
  with:
    name: artifacts_x86_64
    path: /usr/local/build
  /usr/local/manifests
  
    retention-days: 1
    if-no-files-found: warn
/usr/bin/docker exec  47222c51304f4c6fcd5028eace19e6e33f4b75bb30243dead9724980bb4f0db6 sh -c "cat /etc/*release | grep ^ID"
/__e/node16/bin/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

### What did you expect to happen?

The files to upload without error.

### How can we reproduce it?

The latest working version of the action is here: https://github.com/Zopolis4/chromebrew/commits/ca9bccfda7dea1ee7e3a29a2d602a0e27fb4fba6
While the first failing one is here:
https://github.com/Zopolis4/chromebrew/tree/42828bb9718331e9973b59c7c3c0e28c2547a094

### Anything else we need to know?

The action will work using `satmandu/crewbuild:amd64@sha256:8ce37cddc8950a6717c2b6a335580aa4142393926fff0640ec64b6b78ee530b8`, but will fail on `satmandu/crewbuild:amd64@sha256:11987d7f9da04ca647097fec0bd0cb7386741eb6344c98077a668afe663a7276`.

### What version of the action are you using?

3.1.2

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
V4 just dropped and we recommend switching over: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/ Overall a host of improvements and fixes.

The runtime of v4 has switched from node16 to node20 and the issue that you saw points to node16 in the container

**Comment by hthemanttiwari** [comment]
Hi,
