### ISSUE TITLE
Don't use @master in your workflow

### ISSUE THREAD

**Issue by konradpabjan** [actions/upload-artifact#41]
During the beta of GitHub Actions, a lot of documentation (including the README for this action) showed example YAML with `master` being referenced:  

```
uses: actions/upload-artifact@master
```

We currently encourage users to **not** use `master` as a reference whenever an action is being used. Instead, one of the available tags should be used such as:
```
uses: actions/upload-artifact@v1
```

Tags are used alongside semantic versioning to provide a stable experience: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-actions#versioning-your-action

The master branch can abruptly change without notice during development which can cause workflows to unexpectedly fail. If you want to avoid unexpected changes or failures, you should use a tag when referring to a specific version of an action. Tags are added to stable versions that have undergone significant testing and should not change.

The `v2` versions of `download-artifact` and `upload-artifact` are currently in development. Expect changes to start showing up in the `v2-preview` branch. These new changes will eventually be merged into `master` (we will communicate about this in the future) and that will have the potential to break your workflows if you are using `@master` so you will have to react by updating your YAML to use a tag. 

Our telemetry indicates a significant amount of users are using `@master`. Good practice for all actions is to use a tag instead of referencing `@master`.

**Comment by mittalyashu** [comment]
Can we subscribe to this issue for further updates for v2 release?

**Comment by konradpabjan** [comment]
`v2` preview should (optimistic about this🤞) be coming out this week. I'll create another issue with updates and everything once that is out

**Comment by konradpabjan** [comment]
@mittalyashu The `v2-preview` is now out if you're interested 😀 (see the pinned issue in this repo). Took way way longer than I was expecting but it's out now.

Once `v2-preview` has been tested for some time, expect it to be merged into master

**Comment by mittalyashu** [comment]
Sorry for the trouble, thanks for the heads up 😁
