### ISSUE TITLE
[docs] `Upload an Individual File` example doesn't work

### ISSUE THREAD

**Issue by gbryant-arm** [actions/upload-artifact#411]
### What files would you like to change?

[README.md](https://github.com/actions/upload-artifact/blob/65d862660abb392b8c4a3d1195a2108db131dd05/README.md?plain=1#L31)

### What are your suggested changes?

I'm getting the following error when running this workflow:

> a step cannot have both the `uses` and `run` keys

**Comment by konradpabjan** [comment]
Directly copy/pasting works

![Image](https://github.com/actions/upload-artifact/assets/16109154/6b667681-6989-4ad7-960a-79ec5086dcd0)

![Image](https://github.com/actions/upload-artifact/assets/16109154/0308da83-b183-43d1-bbf4-bcaab0b2ee20)

Recommend checking what you had earlier
