### ISSUE TITLE
Upload fails, appears to be looking at the wrong path. (Windows Only)

### ISSUE THREAD

**Issue by kwhat** [actions/upload-artifact#43]
Hi,

Thank you for this plugin.  Everything was working correctly during the beta, however, uploading on windows appears to fail due to a project path being duplicated.  I suspect the path should be `d:\a\PDO\build\coverage` with only one PDO folder.

```
Run actions/upload-artifact@master
  with:
    name: coverage-report
    path: build/coverage
##[error]Path does not exist d:\a\PDO\PDO\build\coverage
##[error]Exit code 1 returned from process: file name 'c:\runners\2.162.0\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by CosasDePuma** [comment]
Same error:

```
with:
    name: mrrobot-amd64-Windows
    path: target/release/mrrobot
##[error]Path does not exist d:\a\MrRobot\MrRobot\target\release\mrrobot
##[error]Exit code 1 returned from process: file name 'c:\runners\2.163.1\bin\Runner.PluginHost.exe', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by mk-pmb** [comment]
Double repo name also on Linux (Ubuntu/Docker):

> Path does not exist /home/runner/work/nodemcu-firmware-daily-vanilla/nodemcu-firmware-daily-vanilla/output

Affected repo: https://github.com/mk-pmb/nodemcu-firmware-daily-vanilla/

**Comment by nuhkoca** [comment]
It is same for me as well, it appends extra repo name to the path

```
##[error]Path does not exist /home/runner/work/calendarview/calendarview/~/junit
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.163.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by mk-pmb** [comment]
The exact steps that had resolved my issue were:
1. In the `path` input variable specify a relative path starting with a directory name and does not traverse up. (Wrong: specify an absolute path i.e. starts with slash. Wrong: specify a relative path that contains a `..` (parent directory) segment)
1. Treat that path as relative to `$GITHUB_WORKSPACE`.

Example config file: [in my repo](https://github.com/mk-pmb/nodemcu-firmware-daily-vanilla/blob/master/.github/workflows/build_firmware.yaml) I use `runs-on: ubuntu-latest` and for the upload action `path: output/`. The `GITHUB_WORKSPACE` environment variable inside the runner usually is set to `/github/workspace/`, so usually my script creates a directory `/github/workspace/output` and stores the artiface file(s) in there.

**Comment by mk-pmb** [comment]
I made an [example repo](https://github.com/mk-pmb/ghaction-examples-upload-artifact/) for Ubuntu, MacOS and Windows, which [seems to work](https://github.com/mk-pmb/ghaction-examples-upload-artifact/commit/a7569efa72f15c4913d34698642f942016ea2269/checks?check_suite_id=390934750) in all of them using the exact same rules as explained above.

So for anyone who still has problems on Windows, please add a debug step before your upload step that checks whether the files you expect actually exist and are inside the `$GITHUB_WORKSPACE` directory. Note I had to wrap the var in `$( … )` for Windows PowerShell.

**Comment by nuhkoca** [comment]
Hi @mk-pmb 

Thanks for the detailed explanation. It helped me indeed! You saved my day!

**Comment by konradpabjan** [comment]
This issue has been fixed with `v2`! The `path` should now properly resolve on Windows.

I ran this bit of YAML to confirm the behavior so it's now identical between Windows/Linux/Mac

```
on:
    push:
        branches:
            -   master

jobs:
    job_example_upload_ubuntu:
        runs-on: ubuntu-latest
        name: '[Ubuntu] Upload artifacts'
        steps:
            -   run: 'mkdir --parents results/artifacts'
            -   run: 'env | grep GITHUB_ | sort > results/artifacts/ci-env.txt'
            -   uses: actions/upload-artifact@v2
                with:
                    name: artifacts_from_ubuntu
                    path: results/artifacts/

    job_example_upload_macos:
        runs-on: macos-latest
        name: '[MacOS] Upload artifacts'
        steps:
            -   run: 'mkdir -p results/artifacts'
            -   run: 'env | grep GITHUB_ | sort > results/artifacts/ci-env.txt'
            -   uses: actions/upload-artifact@v2
                with:
                    name: artifacts_from_macos
                    path: results/artifacts/

    job_example_upload_windows:
        runs-on: windows-latest
        name: '[Windows] Upload artifacts'
        steps:
            -   run: 'mkdir results'
            -   run: 'mkdir results\artifacts'
            -   run: 'dir $( $GITHUB_WORKSPACE )'
            -   run: 'env | Where-Object {$_ | Select-String "GITHUB_"} | sort > results\artifacts\ci-env.txt'
            -   uses: actions/upload-artifact@v2
                with:
                    name: artifacts_from_windows
                    path: results/artifacts/
```

**Comment by mk-pmb** [comment]
I updated my example repo to show the new environment variables, instead now I get [strange provisioning errors](https://github.com/mk-pmb/ghaction-examples-upload-artifact/actions/runs/110452011).
