### ISSUE TITLE
[bug] Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by madhusameena** [actions/upload-artifact#467]
### What happened?

When I use the action

```
- name: Upload artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Build-Artifacts
          path: |
            coverage/
            test-results/*.xml
```
But got the below error

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load actions/upload-artifact/v4.0.0/action.yml
```

Same thing is working fine when I use v3.1.2

### What did you expect to happen?

Upload artifacts

### How can we reproduce it?

Use 4.0 version on Ubuntu 18.04

### What version of the action are you using?

4.0.0

### What are your runner environments?

linux

**Comment by robherley** [comment]
👋 Unfortunately using ubuntu 18.04 runners/images are deprecated: 
- https://github.com/actions/runner-images/issues/6002

You should upgrade your runner version, you'll run into this issue on any actions that uses node20
