### ISSUE TITLE
[feat req] v4: add option to disable the 10 artifacts per job limit

### ISSUE THREAD

**Issue by database64128** [actions/upload-artifact#470]
### What would you like to be added?

An option to remove the limit and restore the old behavior (before v4).

### Why is this needed?

I have a workflow that needs to upload 24 artifacts in a single job. It is not possible to split the workflow into multiple jobs.

**Comment by siegfriedpammer** [comment]
Is there any documentation or explanation for why this limit was added in the first place?

**Comment by JackCoplandGranta** [comment]
Would be useful. we have a build that outputs 15 that caught us out when we tried to upgrade to v4. For anyone else in the same situation you can do a mix to take advantage of the speed gain - pick your 10 largest artifacts in that job and output them using v4, and use v3 for the others.

**Comment by robherley** [comment]
@JackCoplandGranta @siegfriedpammer @database64128 

👋 The limit has been raised to 500 Artifacts per job.

We chose to introduce a limit to avoid abuse scenarios. We did some data analysis, the 10 artifacts limit covered covered ~93% of all the workflow runs on GitHub.

We decided to raise it to 500 to avoid _any_ friction without risk of abuse. Having 500 per job covers 99.99% of runs on GitHub.

**Comment by database64128** [comment]
@robherley Has the limit been raised yet? I'm still seeing the same error.

**Comment by database64128** [comment]
Thanks. 500 sounds like a reasonable limit.
