### ISSUE TITLE
[bug] seeing in v4: com.esotericsoftware.kryo.KryoException: Buffer underflow

### ISSUE THREAD

**Issue by jingwei99** [actions/upload-artifact#476]
### What happened?

In v4, I've seen `com.esotericsoftware.kryo.KryoException: Buffer underflow` for file write, and it doesn't happen for the same configuration for v3. 

### What did you expect to happen?

File gets uploaded without issue.

### How can we reproduce it?

[Link](https://github.com/cashapp/zipline/actions/runs/7229025329/job/19699332079#step:7:3325) to the console output of the github action run. 

The issue doesn't repro when switched back to v3. 

### What version of the action are you using?

v4

### What are your runner environments?

macos

**Comment by konradpabjan** [comment]
Upload happens _after_ the exception already occurs. This should not be at all related in any way.

![Image](https://github.com/actions/upload-artifact/assets/16109154/c783f6a9-64f5-4b29-ac2f-4fce130fc62f)

Have you been able to reproduce this on multiple occasions?

**Comment by jingwei99** [comment]
Hi Konrad 👋 , thanks for looking into this, and for the screenshot. 

I have made another try: 
1) opened a PR, and change the upload action to v4, the same failure reproduced: [link to the run](https://github.com/cashapp/zipline/actions/runs/7267725795/job/19802136347?pr=1208)
2) update the PR, and revert the upload action to v3, the run succeeds, [link to the run](https://github.com/cashapp/zipline/actions/runs/7268369115/job/19805523197?pr=1208)

**Comment by jingwei99** [comment]
Update, ran into the error a few times recently, and saw more symptoms, I think github action version is unrelated to the error. Will close this report!
