### ISSUE TITLE
[bug] (v4) Unable to upload to same artifact name from multiple jobs

### ISSUE THREAD

**Issue by DanTup** [actions/upload-artifact#478]
(Edit: There are solutions posted in this thread such as at https://github.com/actions/upload-artifact/issues/478#issuecomment-1885470013, https://github.com/actions/upload-artifact/issues/478#issuecomment-2016557414)

---

### What happened?

The [PR from dependabot to upgrade to v4](https://github.com/Dart-Code/Dart-Code/pull/4900) is failing on my project with this error:

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

It seems like this is a breaking change that wasn't mentioned in the changelog and I'm not sure if it was deliberate.

There's some discussion about this behaviour in https://github.com/actions/upload-artifact/issues/279 and it suggests that it was fine to do this and there wouldn't be issues as long as the filenames within the artifact are unique. This was convenient to bundle the logs from several shards together into a single artifact rather than having lots of individual zip files to download.

### What did you expect to happen?

I expected everything to work the same as in v3 unless it was noted as a deliberate breaking change.

### How can we reproduce it?

Create multiple jobs that upload artifacts with the same name (but the files from each job are uniquely named).

### What version of the action are you using?

v4.0.0

### What are your runner environments?

linux, window, macos

**Comment by DanTup** [comment]
Actually, it seems this is called out here:

https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new:~:text=The%20contents%20of%20an%20Artifact%20are%20uploaded%20together%20into%20an%20immutable%20archive.%20They%20cannot%20be%20altered%20by%20subsequent%20jobs.%20Both%20of%20these%20factors%20help%20reduce%20the%20possibility%20of%20accidentally%20corrupting%20Artifact%20files.

> The contents of an Artifact are uploaded together into an immutable archive. They cannot be altered by subsequent jobs. Both of these factors help reduce the possibility of accidentally corrupting Artifact files.

It just wasn't included in the "What's changed" section of the Dependabot release notes because it just has a summary saying "Lots has changed". I should've followed the link through.

Seems like this is certainly intended though.

**Comment by RobertoPrevato** [comment]
Well, this is a bad news for me. I find convenient to use the `upload-artifact` to write different files to the same folder in a build matrix. For example to compile custom C extensions for Python for various Python versions and various operating systems, and publishing to a single folder.

like in https://github.com/Neoteroi/BlackSheep/actions/runs/7370452109/job/20056867940

Now if I want to upgrade my workflow, I need to publish to different folders and download artifacts from multiple sources - making the workflow look like a mess compared to how clean it used to look like. For now I stay with `v3` and I hope this will be reconsidered in a future version of these actions.

**Comment by DanTup** [comment]
Yeah, I rolled back to v3 too. Until I'm forced to upgrade, the old way is much more convenient for me.

**Comment by ptr727** [comment]
Same here, I also use a matrix, rolling back to v3 :(

**Comment by ptr727** [comment]
@DanTup may I suggest you reopen this bug as it is getting lots of traction, and let the project owner close it if they deem fit doing so without offering an alternative for e.g. matrix operations dumping to the same folder?

**Comment by DanTup** [comment]
Seems like a lot of people have been bitten by this, so although it appears to have been deliberate I'm re-opening for better visibility to see if the authors want to chime in (of course, it's very possible it may just be closed as WAI).

**Comment by dvarrazzo** [comment]
The behaviour of several jobs saving different files, **with different names**, but in the same directory, to be downloaded from a single archive once all the jobs succeeded, was very desireable and didn't require the use of `actions/download-artifact`.

https://github.com/psycopg/psycopg/blob/fe097e2e4356a4332a54ae21e1c4307bc7c19b4f/.github/workflows/packages-src.yml

Moving to using v4 seems a major change which, for the moment, we will avoid.

**Comment by jsoref** [comment]
There were only [27 commits](https://github.com/actions/upload-artifact/compare/v3...v4.0.0) according to the [v4.0.0 release notes](https://github.com/actions/upload-artifact/releases/tag/v4.0.0).

Breaking changes (and this definitely is a breaking change) should absolutely be called out in major version bump releases' release notes.

It's explicitly included in the readme:
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes

That same text should *absolutely* be included in the release notes.

Conveniently GitHub lets you rewrite release notes at any time, so this can and should be fixed.

@robherley you wrote "Blog post coming soon!" in https://github.com/actions/upload-artifact/pull/466#issue-2040382024, I presume that's:
https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

But it'd be really good if you had added a commentin the PR itself instead of forcing people to Google for it. (You could also include a link to the blog post in the release notes.)

Beyond that, most of its content, which I will excerpt below *should* be in the release notes, and probably in the readme. Note that the readme content does *not* match the blog post.

Blog post first:

> * Artifacts will be scoped to a job rather than a workflow. This allows the artifact to become immediately available to [download from the API](https://docs.github.com/rest/actions/artifacts#download-an-artifact) after being uploaded, which was not possible before.
> * Artifacts `v4` is not cross-compatible with previous versions. For example, an artifact uploaded using `v3` cannot be used with `actions/download-artifact@v4`.
> * Using `upload-artifact@v4` ensures artifacts are immutable, improving performance and protecting objects from corruption, which would often happen with concurrent uploads. [Artifacts should be uploaded separately and then downloaded into a single directory](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact) using the two new inputs, `pattern` and `merge-multiple`, available in `download-artifact@v4`. These objects can then be re-uploaded as a single artifact.
> * A single job can upload a maximum of 10 artifacts.

Readme:

> 1. On self hosted runners, additional [firewall rules](https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes) may be required.
> 1. Uploading to the same named Artifact multiple times.
>     Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you _will_ encounter an error.
> 1. Limit of Artifacts for an individual job. Each job in a workflow run now has a limit of 10 artifacts.

**Comment by liyishuai** [comment]
My data point against v4: Generating documentations.
I have a matrix of jobs (for different versions of build environments), each generates a documentation. I don't want to specify "only generate the docs on this particular version", as the matrix of versions change frequently. I don't care "which" job overwrites the docs generated by "which" other job, as the docs are mostly the same: Just give me any one of them.

The "correct" way of doing things: Name each artifact after the job matrix.
But: The jobs matrix is specified by the docker images e.g. "username/repo:version", which is a bad filename. I really don't want to write a script just to compute a valid filename for the artifact.

**Comment by GyulyVGC** [comment]
Same here, just rolled back to v3 😞

**Comment by jontingvold** [comment]
Just want to chip in that this caused a lot of issues for our company as well.

**Comment by robherley** [comment]
👋 @RobertoPrevato For your example, you don't have to make too many changes, e.g.

https://github.com/Neoteroi/BlackSheep/blob/b283414c88e2d32675a1ca982d937a5dab75b532/.github/workflows/main.yml#L209-L212

Change that line to:

```yaml
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist
```

Then, in your publish job:

https://github.com/Neoteroi/BlackSheep/blob/b283414c88e2d32675a1ca982d937a5dab75b532/.github/workflows/main.yml#L226-L230

You can have it download all the artifacts matching a pattern to the same directory:

```yaml
      - name: Download a distribution artifact
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist
```

This case is outlined in the migration document: https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md

I'm happy to help any others with their workflow scenarios, thanks all for the feedback!

**Comment by RobertoPrevato** [comment]
@robherley Thank You! I appreciate your help very much, I try that as soon as I get the time.

**Comment by RobertoPrevato** [comment]
@robherley I tried what you recommended, and unfortunately I get the following error:

```
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: dist-*
```

https://github.com/Neoteroi/BlackSheep/actions/runs/7506569122/job/20438420140

**Comment by jsoref** [comment]
@robherley 
> Uploads and downloads must use the same actions versions.

It isn't _obvious_ that you mean "the same _major_ action version." -- If that's what's intended.

**Comment by gandarez** [comment]
@robherley saved my life to not downgrading to v3! Thanks!

**Comment by valeriosalvucci** [comment]
I rolled back to v3, too.

**Comment by donfirst** [comment]
I rolled back to v3, too. Anyone knows any  alternative repo for  that - maybe a fork  based on v3 ????

**Comment by jsoref** [comment]
@robherley in https://github.com/actions/upload-artifact/issues/478#issuecomment-1885470013 you pointed to: https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md

I believe I've made a faithful reproduction of your workflow (v3 and v4), and it is *not* a drop-in replacement.
https://github.com/check-spelling-sandbox/artifact-merge-hell/actions/runs/7729203589/job/21071843037

```diff
-Run ls -R my-v3-artifact
-my-v3-artifact:
-my-v3-artifact
-
-my-v3-artifact/my-v3-artifact:
+Run ls -R my-v4-artifact
+my-v4-artifact:
 file-macos-latest.txt
 file-ubuntu-latest.txt
 file-windows-latest.txt
```

Since paths are how people find files, the fact that the paths do not match would break anyone trying to use it.

I'm not sure that's precisely why I gave up, but I can assure you it is one of the problems I encountered.

**Comment by robherley** [comment]
👋 @jsoref apologies, I had a typo in the migration docs.

The reason why you have an extra `my-v3-artifact/my-v3-artifact` in the v3 download is the behavior outlined [here in the v3 docs](https://github.com/actions/download-artifact/tree/v3?tab=readme-ov-file#download-all-artifacts).

> If the name input parameter is not provided, all artifacts will be downloaded. To differentiate between downloaded artifacts, a directory denoted by the artifacts name will be created for each individual artifact.

[These lines](https://github.com/check-spelling-sandbox/artifact-merge-hell/blob/d0517750fe8b6cd830f00413ff108a6cb2cbb247/.github/workflows/artifacts-v3-v4.yml#L22-L23) should be:

```
with:
  name: my-artifact
  path: my-artifact
```

In v4, this behavior is now toggleable with the `merge-multiple` parameter.

I'll update the migration docs to include the `name` parameter.

**Comment by jsoref** [comment]
Thanks, with that change, the results now do look compatible: https://github.com/check-spelling-sandbox/artifact-merge-hell/actions/runs/7730117258

**Comment by ktrzcinx** [comment]
Looks like a https://github.com/actions/upload-artifact/tree/main/merge should be solution for this problem

**Comment by MatthewPattell** [comment]
Take a look at https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact

**Comment by panpuchkov** [comment]
> Solution provided in the [comment](#issuecomment-1885470013), work just fine for v4 actions
> 
> ```yaml
> - name: Upload artifacts
>   uses: actions/upload-artifact@v4
>   with:
>     name: dist-${{ matrix.os }}
>     path: dist
> 
> - name: Download artifacts
>   uses: actions/download-artifact@v4
>   with:
>     pattern: dist-*
>     merge-multiple: true
>     path: dist
> ```

It works like a charm, thank you!

**Comment by stweil** [comment]
Here is an example how it could be solved for BigBlueButton: https://github.com/bigbluebutton/bigbluebutton/pull/19777/commits/0f726d53d6e2795e31ff1500b2e02705ed3d4f8f.

**Comment by kryshenp** [comment]
Rolling back to v3 as well :( 
actions/upload-artifact@v4 broke the entire pipeline, and none of the mentioned solutions solved our problem. 
In our workflow, we run parallel jobs in matrix strategy that generate loads of files that were uploaded into a single results folder in v3. With v4, in our parallel job, we upload a large number of folders with unique names and use one more job action/upload-artifact/merge@v4 to merge these folders into a single one that is downloadable through the UI. 
The solution technically works but is unsuitable for us because we are getting all the artifact folders from parallel jobs uploadable through the UI, which we don't need, and it makes a big mess in our artifacts.

**Comment by kennykerr** [comment]
Also had to revert to v3 here https://github.com/microsoft/cppwinrt/pull/1409

**Comment by stweil** [comment]
@kryshenp, @kennykerr, it's not necessary (and also not a good idea) to revert to v3 (which will stop working in the future). Read my comment above how to fix your code to make v4 working.

**Comment by alonbl** [comment]
Hi,

At first I was also surprise from this breakage, yes it creates an effort of migration and unexpected, I also immediately reverted, but while thinking of it realized why it was done and migrated our usage.

The previous implementation was probably a mistake, the new implementation is more consistent.

The advantages of the new stateless implementation:
1. Artifacts are available immediately after creation, no need to wait until the workflow completes.
2. Implementation is much faster as the artifacts are not merged when not needed, it takes less space to manage the process.
3. Consistent approach of artifacts within workflow or reusable workflow.
4. Consistent approach when running/rerunning partial workflow.

I hope the above helps to understand the WHY, it is easier to perform migration when we understand the WHY.

Thanks,
Alon

**Comment by jennydaman** [comment]
It was just announced that v3 will be disabled on 2024-11-30.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

It is disappointing that the disabling of v3 was announced before v4 reaching feature-completeness.

**Comment by sameeraksc** [comment]
We are having the same issue

**Comment by stweil** [comment]
Then fix your code. The description how to do that can be found above.

**Comment by liyishuai** [comment]
> Take a look at [`main`/docs/MIGRATION.md#overwriting-an-artifact](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md?rgh-link-date=2024-02-02T16%3A55%3A24Z#overwriting-an-artifact)
> 
> ```
>       - name: New override option
>         uses: actions/upload-artifact@v4
>         with:
>           name: build-artifact
>           path: ./example
>           overwrite: true
> ```

Thanks for the notice! Seems like #501 has fixed the issue here.

**Comment by charlieforward9** [comment]
I worked around this problem by appending `${{ github.run_number }}-${{ github.run_attempt }}` to the artifact name. This guarantees a clean, traceable, unique name on every (re)run.

**Comment by dreinhardt89** [comment]
I'm setting `overwrite: true` and still getting this am I missing something?

```
Run actions/upload-artifact@v4
  with:
    name: tf-module-cache-key-file
    retention-days: 3
    path: .terraform/modules/modules.json
    overwrite: true
    if-no-files-found: warn
    compression-level: 6
  
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

**Comment by jsoref** [comment]
@dreinhardt89: you shouldn't use `overwrite: true`, you should give each of your artifacts a distinct name and then use the merge subaction: https://github.com/actions/upload-artifact/blob/main/merge/README.md

**Comment by josephleung5** [comment]
this migration guide should help?
https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md

**Comment by phyzical** [comment]
just an fyi to those holding onto v3

`actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024`

Unsure if this will stop your from staying v3 (incase something occurs github side at that date)

**Comment by maks** [comment]
Yet another user here having to rollback to v3 due to this breaking matrix uploads.

Hopefully this gets addressed by Github before November...

**Comment by stweil** [comment]
@maks, read the instructions and the examples above. Update your code, then there is no need for a rollback.

**Comment by maks** [comment]
@stweil thanks for letting me know, though it would have been easier if you had linked to the specific comment from @robherley  which I somehow missed  [comment](https://github.com/actions/upload-artifact/issues/478#issuecomment-1885470013) in the flood of comments on this issues history and yes using:
```
with:
          name: ${{ matrix.output-name }}
```
 that does indeed fix the issue for me too.

**Comment by air3ijai** [comment]
@maks, and almost all the flood is composed of the messages similar to your or mine ones 😄

Probably we should ask @DanTup to add a link to a [mentioned solution](#issuecomment-1885470013) in it's initial message?

**Comment by stweil** [comment]
See also [my previous comment](https://github.com/actions/upload-artifact/issues/478#issuecomment-2016557414) for a solution.

**Comment by DanTup** [comment]
> Probably we should ask @DanTup to add a link to a [mentioned solution](https://github.com/actions/upload-artifact/issues/478#issuecomment-1885470013) in it's initial message?

I added an edit to the top of the issue to the two comments mentioned directly above.

Closing this as I believe the issue is solved ([I've since migrated to v4 and have the artifacts merged as I had previously with v3](https://github.com/Dart-Code/Dart-Code/commit/c33764811ffb18fb74a787ba7b36073229a3075a)).

**Comment by tvorogme** [comment]
@DanTup I feel this migration so ugly. 

Why it "just work" before, and now you need to do this strange shitty coding -_-

**Comment by DanTup** [comment]
@tvorogme I don't disagree, but this ship has sailed and I don't have any ability to improve it (I'm not a contributor here, I'm just a user that was affected by this change).

**Comment by air3ijai** [comment]
@georgik98, that works. My [post](#issuecomment-1918746908) and mentioned [comment](#issuecomment-1885470013).

We've switched to the v4 for download/upload actions and slightly adjusted workflow.

**Comment by jsoref** [comment]
@awhisler: your matrix appears to have an overlap. That means that _one_ of the other items in the matrix has the same value -- and _that_ is the one that managed to produce an artifact. If you want help, you'd need to provide the workflow.

**Comment by abelbraaksma** [comment]
Unfortunately, we cannot use v3 anymore at all... See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

You'd see the following error:

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`.
```
