### ISSUE TITLE
[feat req] Upload artifact in-place

### ISSUE THREAD

**Issue by rikhuijzer** [actions/upload-artifact#484]
### What would you like to be added?

An option for an artifact upload to remove all previous artifacts with the same `name`.

### Why is this needed?

In many cases, only the most recently generated artifact is useful. For example, when building binaries for private use, older versions are not required. When the binaries are generated only after the tests pass, then they can easily be regenerated by reverting and rebuilding when needed.

Relatedly, most Actions for GitHub Pages allow retaining only the latest version via, for example `force_orphan` (https://github.com/peaceiris/actions-gh-pages).

**Comment by konradpabjan** [comment]
@rikhuijzer Have you seen https://github.com/actions/upload-artifact/issues/338 

Looks like a duplicate

**Comment by rikhuijzer** [comment]
> Looks like a duplicate

Agreed.
