### ISSUE TITLE
[bug]Unable to overwrite upload artifacts

### ISSUE THREAD

**Issue by dabao1955** [actions/upload-artifact#487]
### What happened?

![Screenshot_2023-12-20-18-54-54-81_df198e732186825c8df26e3c5a10d7cd](https://github.com/actions/upload-artifact/assets/79307765/f4e659f9-ed27-4913-a089-6d1f8218dc90)

### What did you expect to happen?

Successful upload of artifacts and overwriting the same artifacts

### How can we reproduce it?

- Create two workflows and use actions/upload-artifact@v4
- Set up the workflow file so that the file names are the same in the upload step
- Report an error

### Anything else we need to know?

There is no this error in v3 version

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by x-mass** [comment]
Take a look to item 2
https://github.com/actions/upload-artifact#breaking-changes

**Comment by dabao1955** [comment]
> Take a look at item 2 https://github.com/actions/upload-artifact#breaking-changes

ok.
