### ISSUE TITLE
[feat req] option to not fail when artifact does exist

### ISSUE THREAD

**Issue by kenorb** [actions/upload-artifact#524]
### What would you like to be added?

In v4 by default action fails if artifact with a matching name does exist.
Please add option to not fail when artifact exist (similar to `if-no-files-found:`), to simply ignore it.

### Why is this needed?

When re-using workflows in job matrix, sometimes it's expected that artifact with the same name exist. Previously when using v3 action, the job didn't fail, but it was merging the files. In v4 since the job fails by default, so I think this new option is needed to have better control over this, otherwise people would be stuck at v3 due to lack of flexibility.

**Comment by comp615** [comment]
Please see #520 and let me know if that covers it (in conjunction with the [details given here](https://github.com/actions/upload-artifact/tree/main/merge#combining-all-artifacts-in-a-workflow-run) on how to use merge to mimic v3 behavior)

**Comment by kenorb** [comment]
Related: GH-549

See: <https://github.com/actions/upload-artifact/blob/v4/docs/MIGRATION.md>
