### ISSUE TITLE
Warning: No files were found with the provided

### ISSUE THREAD

**Issue by neelpai** [actions/upload-artifact#532]
### What happened?

Showing Error :  No files were found with the provided

### What did you expect to happen?

The artifact should be available to download if it's existing in the repository.

### How can we reproduce it?

```name: "Build and deploy Android apps"
on:
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            apk_file=$(find "${{ github.workspace }}" -type f -name '*.apk' -print -quit)
            if [ -z "$apk_file" ]; then
              echo "No APK file found"
              exit 1
            fi
            echo "APK file found: $apk_file"
            echo "$apk_file"
          retention-days: 3
```

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
You can't just input a whole script as an input to `path`. The current documentation states: `# A file, directory or wildcard pattern that describes what to upload`

Currently it's thinking that `apk_file=$(find "${{ github.workspace }}" -type f -name '*.apk' -print -quit)` is the name of one path, `if [ -z "$apk_file" ]; then` is another path, `echo "No APK file found"` etc.

If you want to run a script first to find a path than you have to do that in another step and then pass that in as input. Here is our documentation: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter
