### ISSUE TITLE
How do I get the run number?

### ISSUE THREAD

**Issue by warrenbuckley** [actions/upload-artifact#6]
I am creating my own actions as NodeJS/JavaScript and I am wondering how do I get the build run number, so I can use it to append/amend version numbers for artefacts.

>Uploading artifact 'package-artifacts' from 'd:\a\Take-Out-The-Trash\Take-Out-The-Trash\output' for run #45

As this repo does not show the source for this as its dealt with the plugin `publish`
https://github.com/actions/toolkit/issues/69

Can you give me a pointer on where we can use this information please
/cc @TingluoHuang

**Comment by warrenbuckley** [comment]
Any updates or inputs on this at all please?

/cc @chrispat @damccorm

**Comment by chrispat** [comment]
@warrenbuckley currently we do not have a run number than you can use as a reference externally.  But this is something we need to add.

**Comment by xt0rted** [comment]
I've been using the build number in my versions numbers (`yyyy.m.d.build`), so far this is the only thing missing that's stopping me from moving all of my builds over to actions. Is this value what you're talking about @chrispat?

**Comment by warrenbuckley** [comment]
@chrispat I will close this issue & can we move the discussion over into this one here in the actions toolkit repo - https://github.com/actions/toolkit/issues/65
