### ISSUE TITLE
Upload from macOS fails with 503 error

### ISSUE THREAD

**Issue by jpfeuffer** [actions/upload-artifact#61]
Uploading from macOS github runner with v2-is-almost-here gives me:

```
Received http 503 during chunk upload, will retry at offset 0 after 10 seconds. Received http 503 during chunk upload, will retry at offset 0 after 10 seconds. ##[error]read ECONNRESET
```

**Comment by jpfeuffer** [comment]
Seems to only happen sometimes, but without a retry option, this is a big deficit.
I don't want to re-run my entire pipeline in this case.

**Comment by yacaovsnc** [comment]
We just merged a significant change around uploading to `v2`, could you please give it a try again?  We changed how we manage the tcp connections.

**Comment by konradpabjan** [comment]
Closing out this issue. Early on during the `v2-preview` 503s were not retried when a chunked upload failed. That is no longer the case.

If you're pinned to `@v2` or `@master` (only do this if you're OK with the latest and greatest that sometimes might break), you should be fine.
