### ISSUE TITLE
[bug] Action says my version of actions/upload-artifact is deprecated, but it is not

### ISSUE THREAD

**Issue by thetaiter-swf** [actions/upload-artifact#615]
### What happened?

I was previously using `actions/upload-artifact@v1` and everything was working great. This was an old worrkflow so I hadn't seen it in a long time. When I came back to it and noticed the old version, I went ahead and updated it to the latest version, `actions/upload-artifact@v4`. However, when I made that change, I got this error in the logs:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
I verified that every instance of `actions/upload-artifact` in the workflow is updated to v4, there are not any still left on v1. I was very confused about where it is thinking I am using v1.

I then attempted to change it back to v1 just to get the build working again, and I still got the same error. I then tried every single version (v1, v2, v3, and v4) and none of them work. We cannot build our application until this is resolved, so it is pretty urgent.

### What did you expect to happen?

I expected it to "just work" when I updated the version from `v1` to `v4`. I did not expect it to complain that I am using a version that I am not in fact using.

### How can we reproduce it?

I am not sure, but you can try setting the version to v1, get a successful build, then switch to v4 and see if it happens.

### Anything else we need to know?

v4 of the action is working great in other repositories around or organization. It is only happening in one repository, though I believe this is the only repository that was previously using v1.

### What version of the action are you using?

v4

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No

**Comment by thetaiter-swf** [comment]
I have since tried completely commenting out the upload-artifact steps, and I still get this error. This is a hard blocker without any possible fix at the moment. Pretty urgent that we get this resolve ASAP.

**Comment by SuperFola** [comment]
@joshmgross This is becoming an issue, according to the code, nothing specifies what version is deprecated. What can we do to circumvent this?

**Comment by joshmgross** [comment]
👋 Thanks for the ping, we're taking a look

**Comment by joshmgross** [comment]
@thetaiter-swf @SuperFola we're not able to reproduce this issue on our end.

Is it possible there's a reusable workflow or composite action that is still referencing the deprecated version?

If that's not the case, could you file a support issue so that we can take a closer look?
https://support.github.com/

Feel free to reference this issue in that support request, and please include URLs for the failing runs that are seeing the deprecation warnings and a copy of the workflow files.

**Comment by thetaiter-swf** [comment]
@joshmgross I have already opened a support ticket but have not heard anything on it yet. Here is the ticket:
https://support.github.com/ticket/personal/0/2997649

I will add the information you requested to that ticket.

**Comment by thetaiter-swf** [comment]
The issue was that I was using pull_request_target trigger instead of pull_request trigger, so it was always using the workflow from the target branch instead of the pull_request branch.
