### ISSUE TITLE
Unable to upload artifact when using v4.4.2

### ISSUE THREAD

**Issue by shankarRaman** [actions/upload-artifact#630]
### What happened?

We use proxy for all outbound calls from our self-hosted runners. We noticed that with release `4.4.2` the calls made to the proxy are not passing the credentials which are getting denied by the proxy server. When using `4.4.1` the action passed the credentials without any issue.

### What did you expect to happen?

Expect the action to upload artifacts without issues

### How can we reproduce it?

We are using self-hosted runners with proxy that has authentication and the credentials are stored as secrets

### What version of the action are you using?

v4.4.2

### What are your runner environments?

self-hosted, linux

**Comment by pulkitanz** [comment]
This is breaking a lot of workflows

**Comment by robherley** [comment]
👋 We're looking into this. Please use the `v4` tag which currently points to `v4.4.1` or any version that isn't `v4.4.2`.

**Comment by joshmgross** [comment]
This should be fixed in https://github.com/actions/upload-artifact/releases/tag/v4.4.3, we're working on validating that fully before updating the `v4` major version tag.

**Comment by robherley** [comment]
The `v4` tag has been updated to point to `v4.4.3`

**Comment by robherley** [comment]
The fix has been out for almost a week now, closing
