### ISSUE TITLE
Please follow semantic versioning - don’t break my build 

### ISSUE THREAD

**Issue by iCodeSometime** [actions/upload-artifact#631]
### What would you like to be added?

Please follow semantic versioning.

If the public API is changed, it must not be distributed as a minor release.

### Why is this needed?

For three months in a row now, there have been breaking changes to the public API of this action that were distributed as a minor release.

 - #590 
 - #602 
 - #630 
 
I and my teammates have wasted a significant number of hours tracking down why things have broken, only to realize there’s been a significant change to the behavior of this action, with no major version bump.

**Comment by joshmgross** [comment]
#590 and #630 have been fixed and were not intentional breaking changes.

#602 fully details why we made the decision to ship a breaking change.

**Comment by Paebbels** [comment]
You could have´:
1. release a `v5` with the breaking modification
2. made `v4` print a deprecation message for 2..4 weeks
3. disabled `v4`

Also keep in mind, hidden files in Linux are widely used for settings, but barely hold any secret information. There is almost no security risk to these files, especially as we're talking about Git repositories with local editor or tool configs. Also dot-files are usually not created in a CI job; the pre-exist in the repository itself. Thus, if these files contain secrets, the secret was already exposed by sharing the files in a repository itself.

In my opinion, this was a complete overreaction by GitHub without understanding the problem and the implications.
