### ISSUE TITLE
Deprecation notice: v3 of the artifact actions

### ISSUE THREAD

**Issue by yacaovsnc** [actions/upload-artifact#635]
>Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by sim642** [comment]
I received an email about this, saying

> You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact.

Where can I see the list of my workflows that do and need updating?

I have hundreds of repositories. Clearly GitHub knows this because of how the email was sent out, so I should also be able to look at this list somewhere.

**Comment by SrRyan** [comment]
Hi @sim642 if you still require assistance please seek out help within this [discussion](https://github.com/orgs/community/discussions/142581) or file a support ticket. Thanks!

**Comment by aummengaum50-ctrl** [comment]
> I received an email about this, saying
> 
> > You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact.
> 
> Where can I see the list of my workflows that do and need updating?
> 
> I have hundreds of repositories. Clearly GitHub knows this because of how the email was sent out, so I should also be able to look at this list somewhere.
> 
> **EDIT:** I found https://github.com/actions/upload-artifact/network/dependents?dependent_type=REPOSITORY&owner=sim642, but that lists 0 repositories, so I'm confused.

1975-1974 1973 1973
