### ISSUE TITLE
static url for download the last artifact on the github-api

### ISSUE THREAD

**Issue by sarahBuisson** [actions/upload-artifact#64]
Hello,
I don't know if it's possible or if it's up to your project to show it but... can you expose an url who allow to download the last builded artifact, for a given artifactName and jobName and a repoName ?

Currently github-api give us an url, but it's different for each build and  it suppose we know the last run id.

**Comment by konradpabjan** [comment]
Thanks for opening the issue @sarahBuisson 

We have a similar issue that is requesting a link to the latest artifact: https://github.com/actions/upload-artifact/issues/21

Going to close this since it's effectively a duplicate and so it's easier to track all of the issues.

**Comment by sarahBuisson** [comment]
It don't fix my issue at all. I need a static direct url because I will use-it  inside a npm package.json. Not in a context where I will be able to do a post curl treatment.
