### ISSUE TITLE
Support $HOME in Path Argument

### ISSUE THREAD

**Issue by ccjernigan** [actions/upload-artifact#8]
This is a feature request to support $HOME in the path.

I'm trying to use the upload-artifact action as a step in a CI build. Most of my other steps are saving and storing files based on paths relative to $HOME, so it makes sense to be able to do the same here.

The workaround currently is to hardcode the path.

So currently I do something like this:

    - uses: actions/upload-artifact@v1
      with:
          name: artifacts.zip
          path: /home/runner/my_file

But would like to do this:

    - uses: actions/upload-artifact@v1
      with:
          name: artifacts.zip
          path: ${HOME}/my_file

**Comment by 1138-4EB** [comment]
@ccjernigan, I think that the default path is HOME. Hence, `path: my_file` might work. Did you try it? Note that `my_file` must be a directory. It is not possible to upload files. Please, see #3.

**Comment by ccjernigan** [comment]
I tried setting `working-directory: ${{ home }}` but that didn't seem to work either.

The reason for filing this issue is so that we don't have to rely on `/home/runner` or some other hardcoded path which might break in the future.

I realize that most of the time, artifacts from the build will be in the checked out repo directory.  In my case, I have a multi-module Gradle build so I want to collect artifacts across a series of directories.  I'm doing a find with wildcards and then copying to another directory, and it seems less weird to create that copy in the home directory rather than within the git repo, to avoid namespace between the git repo contents and temp directories created by the CI script.

**Comment by 1138-4EB** [comment]
@ccjernigan, just to make it clear, **I totally agree with this issue/request**. My comments above were an effort to find a currently supported workaround that could have filled your requirements. Unfortunately, it seems that there is none.

> I'm doing a find with wildcards and then copying to another directory, and it seems less weird to create that copy in the home directory rather than within the git repo, to avoid namespace between the git repo contents and temp directories created by the CI script.

I apply a similar procedure, but I use a sibling directory, not a children nor any 'arbitrary' location. E.g.:

```
- run: |
    mkdir ../artifacts
- uses: actions/upload-artifact@v1
  with:
      name: artifacts.zip
      path: ../artifacts
```

Of course, this relies on `run` and `uses: actions/upload-artifact` being executed in exactly the same workspace. I don't know if this is officially guaranteed.

Apart from that, regarding wildcards and reorganizing the content with find/cp, you might want to upvote [this](https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814) comment in #3.

**Comment by natario1** [comment]
Not adding much to the discussion, but it would be nice to be able to use any env variable (not just HOME).

**Comment by MaxPeal** [comment]
+1

**Comment by konradpabjan** [comment]
We've added support for `$HOME` using tilde expansion in the `v2-preview`. You can check it out here:
https://github.com/actions/upload-artifact/issues/62

Using env variables as input to actions was added a while back ago (this was a limitation that was effecting all actions). I've updated our documentation with examples on how to use env variables and tilde expansions: https://github.com/actions/upload-artifact/tree/v2-preview#environment-variables-and-tilde-expansion

**Comment by myitcv** [comment]
Thanks for the update.

> Using env variables as input to actions was added a while back ago

Just to confirm, according to [this page](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context):

> The env context syntax allows you to use the value of an environment variable in your workflow file. If you want to use the value of an environment variable inside a runner, use the runner operating system's normal method for reading environment variables.

i.e. you cannot arbitrarily expand environment variables as input values, for example.

**Comment by konradpabjan** [comment]
`v2` artifact upload has been released and with it there is support of tilde expansion. The`REAMDE` also has an example on how to use this along with env variables: https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion

**Comment by nonesky666** [comment]
aha hm i see thanks
