### ISSUE TITLE
##[error]Artifact path is not valid: /debug-V1.9-DEBUG-28May-08:53AM.apk. Contains character: ":". Invalid characters include: ",:,<,>,|,*,?.

### ISSUE THREAD

**Issue by radheyjat** [actions/upload-artifact#85]
**My generate apk file name is contain Date and Time time in have a **:**  sign So help me out to add : also for wild card character**

**Version**
- [  No ] V1
- [ Yes ] V2

**Environment**
- [  No ] self-hosted
- [ Yes ] Linux
- [  No ] Windows
- [  No ] Mac

**Screenshots**
![Screenshot from 2020-05-28 14-35-43](https://user-images.githubusercontent.com/64408910/83122007-a9d31680-a0f0-11ea-8657-3ca170922fff.png)

**Run/Repo Url**
No My Application is not a public
**How to reproduce**
Add in gradle flavors "APK_NAME+V${version_name_release}-"+ new Date().format("dMMM-hh:mmaa")  generated apk contain date time format

**Comment by konradpabjan** [comment]
This is a deliberate limitation

See our documentation: https://github.com/actions/upload-artifact#additional-documentation and https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md

`:` in particular doesn't play nice with `macos` and we have to remain platform-agnostic. If you create the artifact on one platform, then the expectation is that you can download it without issues on another.

We also do no plan on sanitizing paths or artifact-names for users.
