### ISSUE TITLE
Download an artifact from the command line?

### ISSUE THREAD

**Issue by lava** [actions/upload-artifact#89]
This seems fairly simple, but I'm stumped: I want to download an artifact from the command line.

I have a public repository generating artifacts from a workflow run. By going to the Github Actions UI and navigating to the workflow, I get URL like this and can download the artifacts using my browser:

    https://github.com/tenzir/vast/suites/818406657/artifacts/9003143

On the command line, trying to `curl` the same URL leads to a 404 error.

From #51 we know that this needs a github user account, so I registered a new bot account and gave it "read" access to the repository, and generated a personalized access token with `repo` scope.

However, using this token I **still** get a 404 error when trying to download above url. I believe that is due to the fact that the access token is valid for `api.github.com`, but not for the "regular" github site.

So, my problem is: How do I go from the artifact URL shown in the Github UI to the corresponding api URL that can be used to download the artifact from the command line? Or alternatively, what kind of token do I need to be able to download from the location shown above?

**Comment by konradpabjan** [comment]
We have some APIs for artifacts, you can check them out here: https://developer.github.com/v3/actions/artifacts/

A combination of the list and the download artifact APIs should give you all of the information you need and this will work from any command line. With the download API you can get a redirect URL that will allow you do download an artifact. You just need to make sure to pass in an appropriate token token: https://developer.github.com/v3/#authentication

The APIs are a little bit limited though (the redirect URL is only valid for a minute), and you can't use these APIs when a workflow hasn't finished as the artifacts won't show up yet.

**Comment by lava** [comment]
@konradpabjan I'm afraid you misunderstood the issue. I know how to download an artifact given an API url and how to authenticate that request. A stated in the original description, I created a bot account with correct permissions for that purpose.

The question is, when I  go to the Github Actions UI and see one specific artifact that I would like to download, how do I get to a download link for **that** artifact? The download link that is displayed in the browser is for `github.com` and not for `api.github.com`, like this:

    https://github.com/tenzir/vast/suites/818406657/artifacts/9003143

and I don't know the mapping between this url and the API url that I would need.

**Comment by konradpabjan** [comment]
Apologies for the misunderstanding

The first part of the URL, `818406657` is the check suite id. https://developer.github.com/v3/checks/suites/

The second part of the URL, `9003143` is this artifact ID, you can get that using the list artifact API: https://developer.github.com/v3/actions/artifacts/#list-artifacts-for-a-repository

What you probably need to do to get the artifact ID is to search using the workflow run id: https://developer.github.com/v3/actions/artifacts/#list-workflow-run-artifacts

And to get the workflow run id, you need to use some of our other APIs: https://developer.github.com/v3/actions/workflow-runs/

It might be a little painful, but if you really want to construct the URL yourself you can try this out 😀

**Comment by 89z** [comment]
This works for me:

~~~
curl.exe `
--netrc-file C:\Users\Steven\_netrc `
-L `
-o crystal.zip `
https://api.github.com/repos/crystal-lang/crystal/actions/artifacts/60912181/zip
~~~

Where `_netrc` looks like this:

~~~
default login <USERNAME> password <PERSONAL ACCESS TOKEN>
~~~

**Comment by agabor** [comment]
@89z Great, thanks!

**Comment by jelmd** [comment]
```
curl -u ${user}:${token} ${archive_download_url}

{
  "message": "You must have the actions scope to download artifacts.",
  "documentation_url": "https://docs.github.com/rest/reference/actions#download-an-artifact"
}
```
What in hell does it mean? There is no `artifact` scope in https://github.com/settings/tokens/$tokenid ...

**Comment by howlowck** [comment]
> ```
> curl -u ${user}:${token} ${archive_download_url}
> 
> {
>   "message": "You must have the actions scope to download artifacts.",
>   "documentation_url": "https://docs.github.com/rest/reference/actions#download-an-artifact"
> }
> ```
> 
> What in hell does it mean? There is no `artifact` scope in https://github.com/settings/tokens/$tokenid ...

Maybe the message meant the `workflow` scope.

**Comment by dz0ny** [comment]
If you are using GitHub Action, you can download artifact via token  that is always present 

```
curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o firmware.zip "https://api.github.com/repos/ExpressLRS/ExpressLRS/actions/artifacts/308108746/zip" ```

**Comment by dimaslanjaka** [comment]
> If you are using GitHub Action, you can download artifact via token that is always present
> 
> ```
> curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o firmware.zip "https://api.github.com/repos/ExpressLRS/ExpressLRS/actions/artifacts/308108746/zip" 
> ```

just tried, and only got 1kb of downloaded file

**Comment by DutchKevv** [comment]
Same.. What is the trick?

**Comment by andronat** [comment]
@dimaslanjaka You need the `/zip` at the end.

**Comment by michal2612** [comment]
> just tried, and only got 1kb of downloaded file


If you use GHSE make sure that you selected correct Host server.

> ```shell
> curl -H "Accept: application/vnd.github+json" -H "Authorization: token github_pat_xxxxxxxx" -L -o tmp.zip "https://<your-GHSE-domain>/dimaslanjaka/android-traffic-exchange/actions/runs/8029763220/artifacts/1271862961"
> ```

**Comment by btgoodwin** [comment]
I've been struggling with this for a day as well, trying to use the `actions/upload-artifact` output `artifact-url` in a follow-on step to simply download the artifact and I've not found it.  Every attempt to use curl (even with `token github_pat_xxxxxxxx` vs. just `token xxxxxxxx`) results in 404 even though the link works from a browser just fine.
