### ISSUE TITLE
Option to suppress warning if artifact doesn't exist

### ISSUE THREAD

**Issue by ben-spiller** [actions/upload-artifact#90]
**Describe the bug**
I'm defining a workflow that should upload a file (in this case, some performance stats) if it was generated by my build but I don't want it to generate a warning annotation ("No files were found for the provided path") if it doesn't exist since that's not an error condition in my workflow. Would be helpful to have an option to toggle this behaviour. 

In the meantime I'm going to try to construct a workaround using step options and "if" but it's kindof complex (especially since there's no if exists() function in GitHub Actions currently), so having support for skipping the warning in this action would be helpful

**Version**
- [x] V2

**Environment**
- [x] Linux
- [x] Windows
- [x] Mac

**Comment by konradpabjan** [comment]
I've put out a PR that allows for any warnings to be suppressed. Not sure about some things yet, but if anyone would like to offer some feedback I would greatly appreciate it

PR #104

**Comment by konradpabjan** [comment]
There is now an option to ignore warnings: https://github.com/actions/upload-artifact#customization-if-no-files-are-found

The `v2` tag has been updated with the latest changes
