### ISSUE TITLE
Upload should fail if no files are found

### ISSUE THREAD

**Issue by themakshter** [actions/upload-artifact#91]
As mentioned in your [comment](https://github.com/actions/upload-artifact/issues/47#issuecomment-620738059) in #47, I think it would be good to have the `fail-if-no-files-uploaded` option. I know that a warning is posted, but I do believe that such a case is cause for failure rather than a warning in some cases as the upload containing files is a required check and not just a warning.

**Comment by nathanblair** [comment]
Is there really not even an option to force a failure if there are no files found for uploading?

I think there are plenty alternative ways of handling an upload task not finding files that wouldn't be there; namely that you do a conditional check for the job to be run in the first place. But there are no ways to declare that the job fails if its intended task doesn't actually do anything?

**Comment by konradpabjan** [comment]
Hey everyone! 😃 I've put out a PR that allows for the action to fail if no files are found. Not sure about some things yet, but if anyone would like to offer some feedback I would greatly appreciate it

PR #104

**Comment by konradpabjan** [comment]
The new feature has shipped: https://github.com/actions/upload-artifact#customization-if-no-files-are-found

The `v2` has been updated with the latest changes

**Comment by nathanblair** [comment]
Thanks @konradpabjan 🤘👍👍
