### ISSUE TITLE
[BUG] Uploading to the same artifact shows up with the wrong size in the UI

### ISSUE THREAD

**Issue by webknjaz** [actions/upload-artifact#98]
**Describe the bug**

I have a matrix of jobs that upload dists into the same artifact. The total
size is about **43 MB** but the combined artifact entry shows up as using **1.43 MB** (I think this corresponds to one of the individual files in one of the jobs).

Earlier I used multiple artifacts that I'd combine in a "sync" job into a new one. It used to show up correctly. I suppose this is happening due to some sort of a race condition because they are being uploaded from the matrix of 12 jobs (there's over 20 files there in total).

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [x] Windows
- [x] Mac

**Screenshots**

N/A

**Run/Repo Url**

https://github.com/ansible/pylibssh/actions/runs/171227260

**How to reproduce**

https://github.com/actions/upload-artifact#uploading-to-the-same-artifact

**Additional context**

**Comment by jonorossi** [comment]
We've had the same problem since first using GitHub Actions with a single job, so not a race condition. It shows the file size of the last file to upload to the artifact, likely a GitHub bug rather than an upload-artifact bug.

**Comment by yacaovsnc** [comment]
We are rolling out the bug fix this week.  Thanks for your patience!
